-- Migration: Hybrid Apply System & Apply Clicks Analytics Table

-- 1. Alter public.jobs to add hybrid apply fields and state
alter table public.jobs add column if not exists apply_type text default 'external' check (apply_type in ('external', 'internal'));
alter table public.jobs add column if not exists apply_url text;
alter table public.jobs add column if not exists apply_label text default 'Apply on Company Website';
alter table public.jobs add column if not exists state text;

-- 2. Backfill existing 100 jobs
update public.jobs
set
  apply_type = 'external',
  apply_label = 'Apply on Company Website',
  apply_url = coalesce(apply_url, source_url)
where apply_type is null or apply_url is null or apply_label is null;

update public.jobs
set state = 'Karnataka'
where (state is null or state = '')
  and (location ilike '%Karnataka%' or location ilike '%Bengaluru%' or location ilike '%Mysuru%' or location ilike '%Mangalore%');

update public.jobs
set state = 'Tamil Nadu'
where (state is null or state = '')
  and (location ilike '%Tamil Nadu%' or location ilike '%Chennai%' or location ilike '%Coimbatore%' or location ilike '%Trichy%' or location ilike '%Tiruchirappalli%');

-- 3. Create apply_clicks table
create table if not exists public.apply_clicks (
  id bigint generated by default as identity primary key,
  job_id bigint not null references public.jobs(id) on delete cascade,
  user_id uuid references auth.users(id) on delete set null,
  apply_type text not null default 'external' check (apply_type in ('external', 'internal')),
  clicked_at timestamptz not null default now()
);

create index if not exists apply_clicks_user_idx on public.apply_clicks(user_id, clicked_at desc);
create index if not exists apply_clicks_job_idx on public.apply_clicks(job_id, clicked_at desc);

-- 4. Enable RLS and create policies for apply_clicks
alter table public.apply_clicks enable row level security;

drop policy if exists hirein_apply_clicks_insert on public.apply_clicks;
create policy hirein_apply_clicks_insert on public.apply_clicks for insert to anon, authenticated
with check (user_id is null or user_id = auth.uid());

drop policy if exists hirein_apply_clicks_select on public.apply_clicks;
create policy hirein_apply_clicks_select on public.apply_clicks for select to authenticated
using (
  user_id = auth.uid()
  or public.hirein_has_role(array['admin'])
  or (
    public.hirein_has_role(array['recruiter'])
    and exists (select 1 from public.jobs j where j.id = apply_clicks.job_id and j.created_by = auth.uid())
  )
);

grant select, insert on public.apply_clicks to anon, authenticated;

-- 5. Trigger for validating imports
create or replace function public.validate_job_import()
returns trigger language plpgsql as $$
begin
  if new.apply_type = 'external' then
    if new.apply_url is null or btrim(new.apply_url) = '' then
      raise exception 'External jobs must have a valid apply_url';
    end if;
    if new.source_url is null or btrim(new.source_url) = '' then
      raise exception 'External jobs must have a valid source_url';
    end if;
    if new.company_id is null then
      raise exception 'External jobs must have a valid company_id';
    end if;
    if not exists (select 1 from public.companies where id = new.company_id) then
      raise exception 'company_id % does not exist in companies table', new.company_id;
    end if;
  end if;
  return new;
end;
$$;

drop trigger if exists trg_validate_job_import on public.jobs;
create trigger trg_validate_job_import
  before insert or update on public.jobs
  for each row execute procedure public.validate_job_import();
