-- HireIn AI app schema + RLS. Run in Supabase SQL Editor.
create table if not exists public.profiles(user_id uuid primary key references auth.users(id) on delete cascade,full_name text not null default '',role text not null default 'candidate' check(role in ('candidate','recruiter','admin')),created_at timestamptz not null default now());
insert into public.profiles(user_id,full_name,role) select id,coalesce(raw_user_meta_data->>'full_name',''),'candidate' from auth.users on conflict(user_id) do nothing;
alter table public.jobs add column if not exists created_by uuid references auth.users(id) on delete set null;

alter table public.jobs add column if not exists status text not null default 'published';
alter table public.applications add column if not exists user_id uuid references auth.users(id) on delete set null;
alter table public.applications add column if not exists resume_url text;
alter table public.applications add column if not exists applied_at timestamptz not null default now();
alter table public.applications alter column status set default 'Applied';
create table if not exists public.saved_jobs(id bigint generated by default as identity primary key,user_id uuid not null references auth.users(id) on delete cascade,job_id bigint not null references public.jobs(id) on delete cascade,created_at timestamptz not null default now(),unique(user_id,job_id));
create table if not exists public.ats_history(id bigint generated by default as identity primary key,user_id uuid not null references auth.users(id) on delete cascade,job_id bigint references public.jobs(id) on delete set null,resume_name text not null,score integer not null check(score between 0 and 100),matched_keywords text[] not null default '{}',missing_keywords text[] not null default '{}',suggestions text not null default '',created_at timestamptz not null default now());
create table if not exists public.resumes(id uuid primary key default gen_random_uuid(),user_id uuid not null references auth.users(id) on delete cascade,name text not null,storage_path text not null unique,created_at timestamptz not null default now());
create or replace function public.hirein_has_role(roles text[]) returns boolean language sql stable security definer set search_path=public as $$ select exists(select 1 from public.profiles where user_id=auth.uid() and role=any(roles)); $$;
revoke all on function public.hirein_has_role(text[]) from public;
grant execute on function public.hirein_has_role(text[]) to authenticated;
-- Promote recruiter accounts only from the Supabase SQL Editor, after the user signs up:
-- update public.profiles p set role = 'recruiter' from auth.users u where p.user_id=u.id and u.email='recruiter@example.com';
create or replace function public.handle_new_hirein_user() returns trigger language plpgsql security definer set search_path=public as $$ begin insert into public.profiles(user_id,full_name,role) values(new.id,coalesce(new.raw_user_meta_data->>'full_name',''),'candidate') on conflict(user_id) do nothing; return new; end; $$;
drop trigger if exists on_hirein_auth_user_created on auth.users;
create trigger on_hirein_auth_user_created after insert on auth.users for each row execute procedure public.handle_new_hirein_user();
create or replace function public.prevent_self_role_change() returns trigger language plpgsql set search_path=public as $$ begin if auth.uid() is not null and new.role is distinct from old.role then raise exception 'Only a trusted administrator can change account roles'; end if; return new; end; $$;
drop trigger if exists prevent_hirein_role_change on public.profiles;
create trigger prevent_hirein_role_change before update of role on public.profiles for each row execute procedure public.prevent_self_role_change();
alter table public.profiles enable row level security;

alter table public.jobs enable row level security;
alter table public.applications enable row level security;
alter table public.saved_jobs enable row level security;
alter table public.ats_history enable row level security;
alter table public.resumes enable row level security;

drop policy if exists "Allow public application submissions" on public.applications;
drop policy if exists hirein_profiles_read_self on public.profiles;
create policy hirein_profiles_read_self on public.profiles for select to authenticated using(user_id=auth.uid());

drop policy if exists hirein_jobs_public_read on public.jobs;
create policy hirein_jobs_public_read on public.jobs for select to anon,authenticated using(status in ('published','active'));
drop policy if exists hirein_jobs_owner_read on public.jobs;
create policy hirein_jobs_owner_read on public.jobs for select to authenticated using(created_by=auth.uid() or public.hirein_has_role(array['admin']));
drop policy if exists hirein_jobs_recruiter_insert on public.jobs;
create policy hirein_jobs_recruiter_insert on public.jobs for insert to authenticated with check(created_by=auth.uid() and public.hirein_has_role(array['recruiter','admin']));
drop policy if exists hirein_jobs_recruiter_update on public.jobs;
create policy hirein_jobs_recruiter_update on public.jobs for update to authenticated using(public.hirein_has_role(array['admin']) or (created_by=auth.uid() and public.hirein_has_role(array['recruiter']))) with check(public.hirein_has_role(array['admin']) or (created_by=auth.uid() and public.hirein_has_role(array['recruiter'])));
drop policy if exists hirein_jobs_recruiter_delete on public.jobs;
create policy hirein_jobs_recruiter_delete on public.jobs for delete to authenticated using(public.hirein_has_role(array['admin']) or (created_by=auth.uid() and public.hirein_has_role(array['recruiter'])));

drop policy if exists hirein_apps_candidate_insert on public.applications;
create policy hirein_apps_candidate_insert on public.applications for insert to authenticated with check(user_id=auth.uid());
drop policy if exists hirein_apps_candidate_read on public.applications;
create policy hirein_apps_candidate_read on public.applications for select to authenticated using(user_id=auth.uid() or public.hirein_has_role(array['admin']) or (public.hirein_has_role(array['recruiter']) and exists(select 1 from public.jobs j where j.id=applications.job_id and j.created_by=auth.uid())));
drop policy if exists hirein_apps_recruiter_update on public.applications;
create policy hirein_apps_recruiter_update on public.applications for update to authenticated using(public.hirein_has_role(array['admin']) or (public.hirein_has_role(array['recruiter']) and exists(select 1 from public.jobs j where j.id=applications.job_id and j.created_by=auth.uid()))) with check(public.hirein_has_role(array['admin']) or (public.hirein_has_role(array['recruiter']) and exists(select 1 from public.jobs j where j.id=applications.job_id and j.created_by=auth.uid())));

drop policy if exists hirein_saved_jobs_owner_all on public.saved_jobs;
create policy hirein_saved_jobs_owner_all on public.saved_jobs for all to authenticated using(user_id=auth.uid()) with check(user_id=auth.uid());
drop policy if exists hirein_ats_owner_select on public.ats_history;
create policy hirein_ats_owner_select on public.ats_history for select to authenticated using(user_id=auth.uid());
drop policy if exists hirein_ats_owner_insert on public.ats_history;
create policy hirein_ats_owner_insert on public.ats_history for insert to authenticated with check(user_id=auth.uid());
drop policy if exists hirein_resumes_owner_all on public.resumes;
create policy hirein_resumes_owner_all on public.resumes for all to authenticated using(user_id=auth.uid()) with check(user_id=auth.uid());

grant select on public.jobs to anon,authenticated;
grant select,insert,update,delete on public.jobs to authenticated;
revoke all on public.applications from anon;
grant select,insert,update on public.applications to authenticated;
grant select on public.profiles to authenticated;
grant select,insert,delete on public.saved_jobs to authenticated;
grant select,insert on public.ats_history to authenticated;
grant select,insert,delete on public.resumes to authenticated;

insert into storage.buckets(id,name,public) values('resumes','resumes',false) on conflict(id) do update set public=false;
drop policy if exists hirein_resume_owner_upload on storage.objects;
create policy hirein_resume_owner_upload on storage.objects for insert to authenticated with check(bucket_id='resumes' and (storage.foldername(name))[1]=auth.uid()::text);
drop policy if exists hirein_resume_owner_read on storage.objects;
create policy hirein_resume_owner_read on storage.objects for select to authenticated using(bucket_id='resumes' and ((storage.foldername(name))[1]=auth.uid()::text or public.hirein_has_role(array['admin']) or (public.hirein_has_role(array['recruiter']) and exists(select 1 from public.applications a join public.jobs j on j.id=a.job_id where a.resume_url=name and j.created_by=auth.uid()))));
drop policy if exists hirein_resume_owner_delete on storage.objects;
create policy hirein_resume_owner_delete on storage.objects for delete to authenticated using(bucket_id='resumes' and (storage.foldername(name))[1]=auth.uid()::text);


