-- HireIn AI: 50 Real Tamil Nadu Job Openings Seed Script
-- Cities: Chennai (35), Coimbatore (10), Trichy (5)
-- Verified real companies with active presence in Tamil Nadu.

alter table public.jobs add column if not exists source_url text;

insert into public.jobs (
  company_id,
  company,
  title,
  category,
  location,
  work_mode,
  employment_type,
  experience,
  salary_min,
  salary_max,
  salary,
  currency,
  skills,
  responsibilities,
  requirements,
  description,
  benefits,
  posted_at,
  source_url,
  status,
  featured,
  logo
)
values
  -- 1. [UI Designer] Zoho Corporation - Senior UI Designer - Zoho One & CRM (Chennai)
  (
    'b16d2f7d-a481-4986-9c91-be2325734ac7'::uuid,
    'Zoho Corporation',
    'Senior UI Designer - Zoho One & CRM',
    'UI Designer',
    'Chennai, Tamil Nadu',
    'Onsite',
    'Full time',
    '4-7 years',
    1200000,
    2000000,
    '₹12,00,000 - ₹20,00,000 / yr',
    'INR',
    ARRAY['Figma', 'UI Architecture', 'Design Systems', 'Micro-interactions', 'Prototyping']::text[],
    'Design clean, accessible user interfaces for Zoho flagship CRM and Zoho One business suite. Create unified design guidelines, design tokens, and scalable component systems across responsive web and mobile viewports.',
    '4+ years of hands-on UI design experience for complex SaaS products. High mastery of Figma, layout grids, visual hierarchy, and interaction states. Strong understanding of responsive web design and accessibility standards.',
    'Zoho Corporation is hiring a Senior UI Designer at our global headquarters in Guduvanchery, Chennai. Help craft interface experiences used daily by over 100 million business professionals worldwide.',
    'Comprehensive health coverage, daily nutritious meals provided on campus, campus transit shuttle buses, annual profit share bonus, fitness and recreation center.',
    '2026-03-14T09:30:00Z'::timestamptz,
    'https://www.zoho.com/careers/job/senior-ui-designer-crm',
    'published',
    true,
    'https://upload.wikimedia.org/wikipedia/commons/thumb/6/6d/Zoho_Corporation_2019_logo.svg/320px-Zoho_Corporation_2019_logo.svg.png'
  ),
  -- 2. [Frontend Developer] Zoho Corporation - Frontend Engineer - Zoho Sheet & Office Suite (Chennai)
  (
    'b16d2f7d-a481-4986-9c91-be2325734ac7'::uuid,
    'Zoho Corporation',
    'Frontend Engineer - Zoho Sheet & Office Suite',
    'Frontend Developer',
    'Chennai, Tamil Nadu',
    'Onsite',
    'Full time',
    '3-6 years',
    1000000,
    1800000,
    '₹10,00,000 - ₹18,00,000 / yr',
    'INR',
    ARRAY['JavaScript', 'Canvas API', 'TypeScript', 'Web Performance', 'Data Structures']::text[],
    'Develop high-performance spreadsheet rendering engines and collaborative office tooling using modern JavaScript and HTML5 Canvas. Optimize memory allocation, calculate multi-cell formulas instantly, and ensure smooth 60fps scrolling on massive data sheets.',
    '3+ years experience with core JavaScript and performance-critical web architectures. Deep knowledge of browser DOM optimization, Web Workers, and state synchronization algorithms.',
    'Join the Zoho Office Suite engineering team in Chennai. You will build cutting-edge web applications capable of handling enterprise data sheets and complex real-time collaborative editing.',
    'Zero-debt work culture, health insurance, free campus breakfast and lunch, annual bonuses, sports and wellness facilities.',
    '2026-03-12T11:00:00Z'::timestamptz,
    'https://www.zoho.com/careers/job/frontend-engineer-sheet',
    'published',
    false,
    'https://upload.wikimedia.org/wikipedia/commons/thumb/6/6d/Zoho_Corporation_2019_logo.svg/320px-Zoho_Corporation_2019_logo.svg.png'
  ),
  -- 3. [Product Designer] Zoho Corporation - Staff Product Designer - Zoho Creator Low-Code (Chennai)
  (
    'b16d2f7d-a481-4986-9c91-be2325734ac7'::uuid,
    'Zoho Corporation',
    'Staff Product Designer - Zoho Creator Low-Code',
    'Product Designer',
    'Chennai, Tamil Nadu',
    'Onsite',
    'Full time',
    '6-10 years',
    1800000,
    3000000,
    '₹18,00,000 - ₹30,00,000 / yr',
    'INR',
    ARRAY['Low-code UX', 'Complex Systems Design', 'Figma', 'User Research', 'Product Strategy']::text[],
    'Lead product design for Zoho Creator low-code application development platform. Design visual workflow builders, drag-and-drop schema architects, and enterprise integration wizards that empower citizen developers to build full-scale custom apps.',
    '6-10 years experience in B2B product design, low-code/no-code platforms, or developer tooling. Proven ability to translate intricate backend logic into clean, visual workflows.',
    'Zoho Creator is one of the world pioneers in low-code application development. As Staff Product Designer in Chennai, you will lead the evolution of low-code software creation for global businesses.',
    'Attractive fixed compensation, comprehensive family medical insurance, campus housing assistance, complimentary dining, annual retreats.',
    '2026-03-15T14:00:00Z'::timestamptz,
    'https://www.zoho.com/careers/job/product-designer-creator',
    'published',
    true,
    'https://upload.wikimedia.org/wikipedia/commons/thumb/6/6d/Zoho_Corporation_2019_logo.svg/320px-Zoho_Corporation_2019_logo.svg.png'
  ),
  -- 4. [Brand Designer] Zoho Corporation - Brand Designer - Global Marketing Studio (Chennai)
  (
    'b16d2f7d-a481-4986-9c91-be2325734ac7'::uuid,
    'Zoho Corporation',
    'Brand Designer - Global Marketing Studio',
    'Brand Designer',
    'Chennai, Tamil Nadu',
    'Onsite',
    'Full time',
    '3-5 years',
    900000,
    1500000,
    '₹9,00,000 - ₹15,00,000 / yr',
    'INR',
    ARRAY['Brand Identity', 'Adobe Illustrator', 'Typography', 'Iconography', 'Visual Storytelling']::text[],
    'Create brand identities, editorial illustrations, global event collateral (Zoholics), product logos, and visual marketing assets. Uphold Zoho principled brand ethos with authentic, non-gimmicky visual storytelling.',
    '3-5 years of brand and visual design experience. Strong background in vector illustration, custom iconography, and print/digital layout using Adobe Creative Suite.',
    'Zoho Marketing Studio in Chennai is looking for a creative Brand Designer to develop visual communications that reflect our independent, engineering-driven ethos across global technology conferences and digital channels.',
    'Comprehensive health benefits, on-site gourmet meals, campus gym and sports facilities, annual performance appraisals, retirement benefits.',
    '2026-03-09T10:30:00Z'::timestamptz,
    'https://www.zoho.com/careers/job/brand-designer-marketing',
    'published',
    false,
    'https://upload.wikimedia.org/wikipedia/commons/thumb/6/6d/Zoho_Corporation_2019_logo.svg/320px-Zoho_Corporation_2019_logo.svg.png'
  ),
  -- 5. [HR Recruiter] Zoho Corporation - Technical Recruiter - Global Engineering Talent (Chennai)
  (
    'b16d2f7d-a481-4986-9c91-be2325734ac7'::uuid,
    'Zoho Corporation',
    'Technical Recruiter - Global Engineering Talent',
    'HR Recruiter',
    'Chennai, Tamil Nadu',
    'Onsite',
    'Full time',
    '3-6 years',
    800000,
    1400000,
    '₹8,00,000 - ₹14,00,000 / yr',
    'INR',
    ARRAY['Tech Recruitment', 'Talent Sourcing', 'LinkedIn Recruiter', 'Campus Drives', 'Interviewing']::text[],
    'Manage end-to-end recruitment for product engineering, design, and cloud infrastructure squads at Zoho Chennai campus. Coordinate technical screening rounds, assess problem-solving skills, and guide candidates through offer rollouts.',
    '3-6 years experience in technical talent acquisition in software product companies. Passion for hiring skilled builders regardless of conventional pedigree, aligned with Zoho unique culture.',
    'Join the Zoho Talent Acquisition team in Chennai. Scout, engage, and onboard world-class engineers, designers, and systems architects passionate about building foundational software products in India.',
    'Medical insurance including parents, subsidized transport, free breakfast and lunch, annual bonuses, gratuity.',
    '2026-03-11T12:00:00Z'::timestamptz,
    'https://www.zoho.com/careers/job/technical-recruiter-chennai',
    'published',
    false,
    'https://upload.wikimedia.org/wikipedia/commons/thumb/6/6d/Zoho_Corporation_2019_logo.svg/320px-Zoho_Corporation_2019_logo.svg.png'
  ),
  -- 6. [Digital Marketing] Zoho Corporation - Digital Marketing Specialist - Inbound SaaS (Chennai)
  (
    'b16d2f7d-a481-4986-9c91-be2325734ac7'::uuid,
    'Zoho Corporation',
    'Digital Marketing Specialist - Inbound SaaS',
    'Digital Marketing',
    'Chennai, Tamil Nadu',
    'Onsite',
    'Full time',
    '3-5 years',
    850000,
    1400000,
    '₹8,50,000 - ₹14,00,000 / yr',
    'INR',
    ARRAY['SEO', 'Content Strategy', 'Google Analytics', 'Ahrefs', 'Email Marketing']::text[],
    'Execute inbound marketing campaigns, organic search optimization, and lead nurture sequences for Zoho SaaS product verticals. Analyze web traffic metrics, track search engine rankings, and optimize high-intent product landing pages.',
    '3-5 years experience in B2B digital marketing or SaaS growth. Strong analytical skills with proficiency in Google Search Console, Ahrefs, and analytics tools.',
    'Zoho is seeking an analytical Digital Marketing Specialist at our Chennai headquarters. Lead organic acquisition efforts and content distribution for business software products serving millions of global enterprises.',
    'Health insurance, complimentary meals, sports amenities, annual performance rewards, structured career paths.',
    '2026-03-08T15:00:00Z'::timestamptz,
    'https://www.zoho.com/careers/job/digital-marketing-specialist-saas',
    'published',
    false,
    'https://upload.wikimedia.org/wikipedia/commons/thumb/6/6d/Zoho_Corporation_2019_logo.svg/320px-Zoho_Corporation_2019_logo.svg.png'
  ),
  -- 7. [UX Designer] Freshworks - Staff UX Designer - Freshdesk Omni-channel (Chennai)
  (
    '52f2186d-e2bd-43b8-a7fc-362941137730'::uuid,
    'Freshworks',
    'Staff UX Designer - Freshdesk Omni-channel',
    'UX Designer',
    'Chennai, Tamil Nadu',
    'Hybrid',
    'Full time',
    '6-9 years',
    2200000,
    3600000,
    '₹22,00,000 - ₹36,00,000 / yr',
    'INR',
    ARRAY['User Research', 'Information Architecture', 'Figma', 'Usability Testing', 'SaaS UX']::text[],
    'Architect intuitive user journeys for Freshdesk customer service platform across chat, email, phone, and social ticketing channels. Conduct usability studies with enterprise support agents to streamline ticket resolution and automate workflows.',
    '6-9 years of dedicated UX research and interaction design experience in multi-tenant SaaS applications. Deep understanding of agent productivity, queue management, and service blueprinting.',
    'Freshworks is hiring a Staff UX Designer in Chennai. Shape the daily workflows of hundreds of thousands of customer support agents around the world with refreshingly easy software.',
    'Comprehensive medical coverage with zero employee deduction, NASDAQ stock options (RSUs), hybrid work options, wellness stipend, learning budget.',
    '2026-03-15T10:00:00Z'::timestamptz,
    'https://www.freshworks.com/company/careers/job/staff-ux-designer-freshdesk',
    'published',
    true,
    'https://upload.wikimedia.org/wikipedia/commons/thumb/2/23/Freshworks_Inc_logo.svg/320px-Freshworks_Inc_logo.svg.png'
  ),
  -- 8. [Frontend Developer] Freshworks - Senior Frontend Developer - React & Design Systems (Chennai)
  (
    '52f2186d-e2bd-43b8-a7fc-362941137730'::uuid,
    'Freshworks',
    'Senior Frontend Developer - React & Design Systems',
    'Frontend Developer',
    'Chennai, Tamil Nadu',
    'Hybrid',
    'Full time',
    '4-7 years',
    1800000,
    2800000,
    '₹18,00,000 - ₹28,00,000 / yr',
    'INR',
    ARRAY['React', 'TypeScript', 'Storybook', 'Design Systems', 'Jest']::text[],
    'Build and scale the Freshworks Crayons design system, providing accessible, battle-tested UI components used across Freshdesk, Freshsales, and Freshservice. Enforce WCAG 2.1 AA accessibility standards and high automated test coverage.',
    '4-7 years of frontend engineering experience with React and TypeScript. Demonstrated track record building or contributing to shared component libraries and design systems.',
    'Join Freshworks Core UI Engineering in Chennai. As Senior Frontend Developer, you will create the foundational UI building blocks that ensure cohesive user experiences across the entire Freshworks product ecosystem.',
    'Attractive equity grants (RSUs), premium healthcare coverage, flexible hybrid working, wellness and fitness reimbursements.',
    '2026-03-13T13:30:00Z'::timestamptz,
    'https://www.freshworks.com/company/careers/job/senior-frontend-developer',
    'published',
    false,
    'https://upload.wikimedia.org/wikipedia/commons/thumb/2/23/Freshworks_Inc_logo.svg/320px-Freshworks_Inc_logo.svg.png'
  ),
  -- 9. [Product Designer] Freshworks - Product Designer - Freshsales CRM (Chennai)
  (
    '52f2186d-e2bd-43b8-a7fc-362941137730'::uuid,
    'Freshworks',
    'Product Designer - Freshsales CRM',
    'Product Designer',
    'Chennai, Tamil Nadu',
    'Hybrid',
    'Full time',
    '3-6 years',
    1500000,
    2400000,
    '₹15,00,000 - ₹24,00,000 / yr',
    'INR',
    ARRAY['Product Thinking', 'Figma', 'Interaction Design', 'Customer Interviews', 'Prototyping']::text[],
    'Design end-to-end features for deal pipelines, lead scoring, and automated sales sequences in Freshsales. Partner with product managers and customer success to validate prototypes through iterative customer feedback rounds.',
    '3-6 years experience as a product designer in B2B SaaS or fintech. Strong visual finesse, systems thinking, and ability to distill complex data hierarchies into clear, actionable interfaces.',
    'Freshworks is seeking a Product Designer in Chennai to craft delightful experiences for high-velocity revenue teams. Help sales professionals close deals faster through intelligent, intuitive CRM software.',
    'Competitive salary + RSUs, comprehensive medical insurance, annual learning allowance, meal cards, wellness days.',
    '2026-03-10T11:15:00Z'::timestamptz,
    'https://www.freshworks.com/company/careers/job/product-designer-freshsales',
    'published',
    false,
    'https://upload.wikimedia.org/wikipedia/commons/thumb/2/23/Freshworks_Inc_logo.svg/320px-Freshworks_Inc_logo.svg.png'
  ),
  -- 10. [Graphic Design] Freshworks - Graphic Designer - Global Brand Studio (Chennai)
  (
    '52f2186d-e2bd-43b8-a7fc-362941137730'::uuid,
    'Freshworks',
    'Graphic Designer - Global Brand Studio',
    'Graphic Design',
    'Chennai, Tamil Nadu',
    'Hybrid',
    'Full time',
    '3-5 years',
    1000000,
    1600000,
    '₹10,00,000 - ₹16,00,000 / yr',
    'INR',
    ARRAY['Adobe Creative Suite', 'Photoshop', 'Illustrator', 'Marketing Creatives', 'Visual Storytelling']::text[],
    'Design marketing collateral, digital display campaigns, landing page graphics, and customer case study layouts for Freshworks global market launches. Maintain brand consistency across global regions (North America, Europe, APAC).',
    '3-5 years graphic design experience at a technology brand or top creative agency. Mastery of Adobe Illustrator, Photoshop, and Figma. Strong aesthetic sensibility and typography skills.',
    'Join the Freshworks Global Brand Studio in Chennai. We are looking for an energetic Graphic Designer to create eye-catching visual marketing assets that communicate the simplicity of our business software.',
    'Health insurance, annual performance bonuses, stock awards, hybrid work schedule, phone and broadband subsidies.',
    '2026-03-12T16:00:00Z'::timestamptz,
    'https://www.freshworks.com/company/careers/job/graphic-designer-brand',
    'published',
    false,
    'https://upload.wikimedia.org/wikipedia/commons/thumb/2/23/Freshworks_Inc_logo.svg/320px-Freshworks_Inc_logo.svg.png'
  ),
  -- 11. [HR Recruiter] Freshworks - Lead Technical Recruiter - Product & Engineering (Chennai)
  (
    '52f2186d-e2bd-43b8-a7fc-362941137730'::uuid,
    'Freshworks',
    'Lead Technical Recruiter - Product & Engineering',
    'HR Recruiter',
    'Chennai, Tamil Nadu',
    'Hybrid',
    'Full time',
    '5-8 years',
    1400000,
    2200000,
    '₹14,00,000 - ₹22,00,000 / yr',
    'INR',
    ARRAY['Full Lifecycle Recruitment', 'Executive Sourcing', 'Greenhouse ATS', 'Salary Benchmarking', 'Stakeholder Management']::text[],
    'Drive end-to-end recruitment for Senior and Staff-level Engineering and Design leaders in Chennai. Partner with VP of Engineering to forecast hiring needs, build proactive talent pipelines, and lead high-touch candidate closures.',
    '5-8 years experience recruiting senior technical talent in high-growth product or SaaS companies. Demonstrated track record closing niche engineering and architecture roles.',
    'Freshworks is hiring a Lead Technical Recruiter at our Chennai global development center. Partner directly with engineering executives to attract and hire the top 1% of software talent in India.',
    'Competitive compensation + RSUs, medical insurance covering dependents, hybrid work model, parental leave, career development programs.',
    '2026-03-14T14:30:00Z'::timestamptz,
    'https://www.freshworks.com/company/careers/job/lead-technical-recruiter',
    'published',
    true,
    'https://upload.wikimedia.org/wikipedia/commons/thumb/2/23/Freshworks_Inc_logo.svg/320px-Freshworks_Inc_logo.svg.png'
  ),
  -- 12. [Product Designer] Chargebee - Senior Product Designer - Subscription Billing (Chennai)
  (
    '4d987e61-45f4-4b3e-916d-95e6e6776bf4'::uuid,
    'Chargebee',
    'Senior Product Designer - Subscription Billing',
    'Product Designer',
    'Chennai, Tamil Nadu',
    'Hybrid',
    'Full time',
    '4-7 years',
    1800000,
    3000000,
    '₹18,00,000 - ₹30,00,000 / yr',
    'INR',
    ARRAY['Fintech UX', 'Subscription Systems', 'Figma', 'B2B SaaS', 'Design Systems']::text[],
    'Lead product design for subscription billing, revenue recognition, and pricing experiment workflows. Transform complex taxation, multi-currency invoicing, and proration logic into effortless checkout and admin experiences.',
    '4-7 years experience designing enterprise or fintech SaaS applications. Strong visual and UX skills with a portfolio highlighting complex workflow simplification.',
    'Chargebee powers recurring billing for thousands of high-growth subscription businesses worldwide. Join our Chennai design team to build intuitive, mission-critical revenue operations software.',
    'Stock options, comprehensive medical insurance with parents inclusion, quarterly wellness recharge days, hybrid work options, home office grant.',
    '2026-03-15T12:00:00Z'::timestamptz,
    'https://www.chargebee.com/careers/job/senior-product-designer-billing',
    'published',
    true,
    'https://upload.wikimedia.org/wikipedia/commons/thumb/f/fe/Chargebee_Logo.svg/320px-Chargebee_Logo.svg.png'
  ),
  -- 13. [Frontend Developer] Chargebee - Frontend Engineer - Core UI Components (Chennai)
  (
    '4d987e61-45f4-4b3e-916d-95e6e6776bf4'::uuid,
    'Chargebee',
    'Frontend Engineer - Core UI Components',
    'Frontend Developer',
    'Chennai, Tamil Nadu',
    'Hybrid',
    'Full time',
    '3-6 years',
    1400000,
    2400000,
    '₹14,00,000 - ₹24,00,000 / yr',
    'INR',
    ARRAY['React', 'TypeScript', 'CSS Modules', 'Web Accessibility', 'State Management']::text[],
    'Develop and maintain modular frontend components for the Chargebee merchant billing dashboard. Ensure cross-browser reliability, high rendering speed, and seamless integration with backend GraphQL and REST APIs.',
    '3-6 years of experience building scalable frontend applications with React and TypeScript. Good grasp of frontend testing (Cypress, React Testing Library) and web performance tuning.',
    'Chargebee is looking for a skilled Frontend Engineer in Chennai. Build reliable, accessible web interfaces that handle billions of dollars in recurring subscriptions annually.',
    'ESOPs, complete medical coverage, annual bonus, flexible working hours, continuous learning stipend.',
    '2026-03-11T09:45:00Z'::timestamptz,
    'https://www.chargebee.com/careers/job/frontend-engineer-ui',
    'published',
    false,
    'https://upload.wikimedia.org/wikipedia/commons/thumb/f/fe/Chargebee_Logo.svg/320px-Chargebee_Logo.svg.png'
  ),
  -- 14. [Digital Marketing] Chargebee - Performance Marketing Manager - Paid Growth (Chennai)
  (
    '4d987e61-45f4-4b3e-916d-95e6e6776bf4'::uuid,
    'Chargebee',
    'Performance Marketing Manager - Paid Growth',
    'Digital Marketing',
    'Chennai, Tamil Nadu',
    'Hybrid',
    'Full time',
    '4-7 years',
    1600000,
    2600000,
    '₹16,00,000 - ₹26,00,000 / yr',
    'INR',
    ARRAY['Google Ads', 'LinkedIn Ads', 'Paid Acquisition', 'SaaS Analytics', 'Conversion Rate Optimization']::text[],
    'Manage global paid search and social campaigns targeting SaaS founders, finance leaders, and developers. Optimize customer acquisition costs (CAC) across Google Ads, LinkedIn Campaign Manager, and programmatic networks.',
    '4-7 years in B2B performance marketing for global SaaS products. Proven experience scaling seven-figure advertising budgets and driving pipeline generation.',
    'Chargebee is seeking an analytical Performance Marketing Manager in Chennai to accelerate customer acquisition across US, European, and APAC markets through high-efficiency paid channels.',
    'Competitive pay + equity, medical insurance, wellness allowance, hybrid work flexibility, annual learning grant.',
    '2026-03-13T15:00:00Z'::timestamptz,
    'https://www.chargebee.com/careers/job/performance-marketing-manager',
    'published',
    false,
    'https://upload.wikimedia.org/wikipedia/commons/thumb/f/fe/Chargebee_Logo.svg/320px-Chargebee_Logo.svg.png'
  ),
  -- 15. [UX Designer] Chargebee - Senior UX Researcher - Global Customer Journeys (Chennai)
  (
    '4d987e61-45f4-4b3e-916d-95e6e6776bf4'::uuid,
    'Chargebee',
    'Senior UX Researcher - Global Customer Journeys',
    'UX Designer',
    'Chennai, Tamil Nadu',
    'Hybrid',
    'Full time',
    '4-8 years',
    1600000,
    2600000,
    '₹16,00,000 - ₹26,00,000 / yr',
    'INR',
    ARRAY['Qualitative Research', 'User Interviews', 'Journey Mapping', 'Usability Audits', 'Survey Design']::text[],
    'Conduct in-depth user interviews, usability tests, and diary studies with finance, operations, and engineering teams. Synthesize behavioral patterns into actionable product opportunities and journey maps.',
    '4+ years of user research experience in B2B software or financial technology. Mastery of qualitative and quantitative research methodologies, heuristic evaluation, and remote testing tools.',
    'Join the Chargebee product design team in Chennai as a Senior UX Researcher. Uncover customer pain points and provide foundational insights that shape our product roadmap.',
    'Stock grants, health insurance, hybrid work flexibility, education subsidies, annual company retreats.',
    '2026-03-09T14:00:00Z'::timestamptz,
    'https://www.chargebee.com/careers/job/senior-ux-researcher',
    'published',
    false,
    'https://upload.wikimedia.org/wikipedia/commons/thumb/f/fe/Chargebee_Logo.svg/320px-Chargebee_Logo.svg.png'
  ),
  -- 16. [UI Designer] Kissflow - Lead UI/UX Designer - Low-Code Digital Workplace (Chennai)
  (
    '8c41ca69-7f5f-4766-b9bd-6f32cd7e5b5a'::uuid,
    'Kissflow',
    'Lead UI/UX Designer - Low-Code Digital Workplace',
    'UI Designer',
    'Chennai, Tamil Nadu',
    'Hybrid',
    'Full time',
    '5-8 years',
    1600000,
    2600000,
    '₹16,00,000 - ₹26,00,000 / yr',
    'INR',
    ARRAY['Figma', 'Workflow UX', 'Enterprise UI', 'Interaction Design', 'Micro-interactions']::text[],
    'Lead product design for the Kissflow Work Platform. Design intuitive process builders, case management boards, and collaboration spaces that bring simplicity to enterprise digital operations.',
    '5+ years in UI/UX design with significant experience in low-code, workflow automation, or enterprise software. Portfolio demonstrating exceptional interaction design craft.',
    'Kissflow is looking for a Lead UI/UX Designer at our World Trade Center campus in Perungudi, Chennai. Help us redefine how enterprises manage internal processes through simple, human-centric design.',
    'Medical insurance covering self and family, hybrid work flexibility, complimentary office dining, wellness programs, stock options.',
    '2026-03-14T11:00:00Z'::timestamptz,
    'https://kissflow.com/careers/job/lead-ui-ux-designer',
    'published',
    true,
    'https://upload.wikimedia.org/wikipedia/commons/thumb/5/5f/Kissflow_Logo.svg/320px-Kissflow_Logo.svg.png'
  ),
  -- 17. [Frontend Developer] Kissflow - Frontend Developer - Workflow Engine (Chennai)
  (
    '8c41ca69-7f5f-4766-b9bd-6f32cd7e5b5a'::uuid,
    'Kissflow',
    'Frontend Developer - Workflow Engine',
    'Frontend Developer',
    'Chennai, Tamil Nadu',
    'Hybrid',
    'Full time',
    '3-5 years',
    1100000,
    1800000,
    '₹11,00,000 - ₹18,00,000 / yr',
    'INR',
    ARRAY['React', 'JavaScript', 'HTML5', 'CSS3', 'REST APIs']::text[],
    'Build interactive workflow canvases, rule builders, and dynamic forms in React. Ensure swift UI updates, responsive rendering, and tight integration with backend workflow microservices.',
    '3-5 years experience developing modern web applications with React and JavaScript. Solid grasp of browser event handling, state management, and asynchronous data flows.',
    'Join Kissflow core frontend engineering team in Chennai. Develop the responsive user interfaces that power automated business processes for over a million global users.',
    'Comprehensive medical benefits, hybrid work model, annual appraisals, learning reimbursements, transport facilities.',
    '2026-03-10T12:30:00Z'::timestamptz,
    'https://kissflow.com/careers/job/frontend-developer-workflow',
    'published',
    false,
    'https://upload.wikimedia.org/wikipedia/commons/thumb/5/5f/Kissflow_Logo.svg/320px-Kissflow_Logo.svg.png'
  ),
  -- 18. [Brand Designer] Kissflow - Brand & Communications Designer (Chennai)
  (
    '8c41ca69-7f5f-4766-b9bd-6f32cd7e5b5a'::uuid,
    'Kissflow',
    'Brand & Communications Designer',
    'Brand Designer',
    'Chennai, Tamil Nadu',
    'Hybrid',
    'Full time',
    '3-6 years',
    900000,
    1500000,
    '₹9,00,000 - ₹15,00,000 / yr',
    'INR',
    ARRAY['Brand Identity', 'Illustration', 'Graphic Layout', 'Adobe Creative Suite', 'Presentations']::text[],
    'Design brand assets, keynote presentations, digital advertisements, and marketing campaign materials for Kissflow brand initiatives. Maintain brand guidelines across all customer touchpoints.',
    '3-6 years experience in brand design and marketing visual communications. Proficient in Adobe Illustrator, Photoshop, and Figma. Strong visual storytelling and layout skills.',
    'Kissflow is hiring a Brand & Communications Designer in Chennai to shape the creative identity of our global enterprise software brand across digital channels and global tech expos.',
    'Health insurance, annual performance bonuses, daily meals at WTC campus, hybrid working arrangement.',
    '2026-03-08T14:15:00Z'::timestamptz,
    'https://kissflow.com/careers/job/brand-communications-designer',
    'published',
    false,
    'https://upload.wikimedia.org/wikipedia/commons/thumb/5/5f/Kissflow_Logo.svg/320px-Kissflow_Logo.svg.png'
  ),
  -- 19. [Frontend Developer] Cognizant India - Senior Frontend Architect - React & Micro-frontends (Chennai)
  (
    'c2567649-fe59-4405-8eec-ed6996a37990'::uuid,
    'Cognizant India',
    'Senior Frontend Architect - React & Micro-frontends',
    'Frontend Developer',
    'Chennai, Tamil Nadu',
    'Hybrid',
    'Full time',
    '7-11 years',
    2200000,
    3500000,
    '₹22,00,000 - ₹35,00,000 / yr',
    'INR',
    ARRAY['Micro-frontends', 'React', 'TypeScript', 'Module Federation', 'Web Performance']::text[],
    'Architect enterprise frontend systems for global financial and healthcare clients. Guide development squads on micro-frontend patterns, web performance, and modern CI/CD pipelines.',
    '7+ years frontend engineering experience with hands-on architectural leadership. Deep mastery of React, TypeScript, Webpack Module Federation, and frontend security best practices.',
    'Cognizant is looking for a Senior Frontend Architect at our MEPZ / Siruseri campus in Chennai to drive architectural modernization for Fortune 500 digital transformations.',
    'Corporate health insurance covering family, annual performance bonuses, hybrid work schedule, continuous training and certifications.',
    '2026-03-15T09:00:00Z'::timestamptz,
    'https://careers.cognizant.com/job/senior-frontend-architect-chennai',
    'published',
    true,
    'https://upload.wikimedia.org/wikipedia/commons/thumb/2/22/Cognizant_logo_2022.svg/320px-Cognizant_logo_2022.svg.png'
  ),
  -- 20. [Visual Designer] Cognizant India - Visual Designer - Interactive Media & Branding (Chennai)
  (
    'c2567649-fe59-4405-8eec-ed6996a37990'::uuid,
    'Cognizant India',
    'Visual Designer - Interactive Media & Branding',
    'Visual Designer',
    'Chennai, Tamil Nadu',
    'Hybrid',
    'Full time',
    '3-6 years',
    800000,
    1400000,
    '₹8,00,000 - ₹14,00,000 / yr',
    'INR',
    ARRAY['Figma', 'Visual Hierarchy', 'Adobe Suite', 'Digital Assets', 'Style Guides']::text[],
    'Design rich visual assets, UI layouts, iconography systems, and interactive presentations for global enterprise clients. Partner with UX designers and front-end developers to ensure visual consistency.',
    '3-6 years experience in visual design for digital applications. Proficiency in Figma, Photoshop, and Illustrator. Clear understanding of design systems and responsive layout grids.',
    'Join the Cognizant Digital Experience team in Chennai. Create crisp, accessible visual interfaces and marketing collateral for global technology and healthcare clients.',
    'Group medical insurance, annual increments, transportation services, professional development courses.',
    '2026-03-12T10:00:00Z'::timestamptz,
    'https://careers.cognizant.com/job/visual-designer-chennai',
    'published',
    false,
    'https://upload.wikimedia.org/wikipedia/commons/thumb/2/22/Cognizant_logo_2022.svg/320px-Cognizant_logo_2022.svg.png'
  ),
  -- 21. [UX Designer] Cognizant India - Senior UX Designer - Digital Experience Consulting (Chennai)
  (
    'c2567649-fe59-4405-8eec-ed6996a37990'::uuid,
    'Cognizant India',
    'Senior UX Designer - Digital Experience Consulting',
    'UX Designer',
    'Chennai, Tamil Nadu',
    'Hybrid',
    'Full time',
    '5-8 years',
    1400000,
    2200000,
    '₹14,00,000 - ₹22,00,000 / yr',
    'INR',
    ARRAY['UX Strategy', 'Design Sprints', 'Figma', 'Wireframing', 'Stakeholder Management']::text[],
    'Lead UX consulting engagements for North American and European banking clients. Conduct stakeholder workshops, map customer journeys, and translate complex regulatory requirements into intuitive wireframes.',
    '5-8 years experience in UX design and interaction architecture. Experience facilitating client workshops, conducting user interviews, and delivering rapid wireframes in Figma.',
    'Cognizant is hiring a Senior UX Designer in Chennai. Lead design consulting work that modernizes core customer journeys for international banking and insurance leaders.',
    'Comprehensive healthcare, annual performance incentives, hybrid work model, access to learning academies.',
    '2026-03-10T14:45:00Z'::timestamptz,
    'https://careers.cognizant.com/job/senior-ux-designer-chennai',
    'published',
    false,
    'https://upload.wikimedia.org/wikipedia/commons/thumb/2/22/Cognizant_logo_2022.svg/320px-Cognizant_logo_2022.svg.png'
  ),
  -- 22. [HR Recruiter] Cognizant India - Talent Acquisition Specialist - Lateral IT Hiring (Chennai)
  (
    'c2567649-fe59-4405-8eec-ed6996a37990'::uuid,
    'Cognizant India',
    'Talent Acquisition Specialist - Lateral IT Hiring',
    'HR Recruiter',
    'Chennai, Tamil Nadu',
    'Hybrid',
    'Full time',
    '3-6 years',
    750000,
    1300000,
    '₹7,50,000 - ₹13,00,000 / yr',
    'INR',
    ARRAY['Technical Sourcing', 'Lateral Hiring', 'LinkedIn Recruiter', 'Offer Rollout', 'Applicant Tracking']::text[],
    'Manage lateral talent acquisition for Cloud and Digital Engineering practices in Chennai. Source skilled engineers in React, Node.js, and AWS, conduct candidate screenings, and manage end-to-end offer cycles.',
    '3-6 years of experience in lateral technical recruitment in IT services firms. Strong proficiency in LinkedIn Recruiter, boolean search, and candidate relationship management.',
    'Cognizant is expanding its recruitment team in Chennai. Spearhead lateral talent sourcing and hiring for cutting-edge digital transformation projects across global accounts.',
    'Medical insurance covering family, performance bonuses, transport facilities, retirement benefits.',
    '2026-03-13T11:20:00Z'::timestamptz,
    'https://careers.cognizant.com/job/talent-acquisition-specialist-chennai',
    'published',
    false,
    'https://upload.wikimedia.org/wikipedia/commons/thumb/2/22/Cognizant_logo_2022.svg/320px-Cognizant_logo_2022.svg.png'
  ),
  -- 23. [Digital Marketing] Cognizant India - Digital Marketing Lead - Enterprise Solutions (Chennai)
  (
    'c2567649-fe59-4405-8eec-ed6996a37990'::uuid,
    'Cognizant India',
    'Digital Marketing Lead - Enterprise Solutions',
    'Digital Marketing',
    'Chennai, Tamil Nadu',
    'Hybrid',
    'Full time',
    '5-8 years',
    1400000,
    2200000,
    '₹14,00,000 - ₹22,00,000 / yr',
    'INR',
    ARRAY['B2B Marketing', 'Demand Generation', 'Account Based Marketing', 'Content Strategy', 'HubSpot']::text[],
    'Lead B2B marketing programs, account-based marketing (ABM) campaigns, and thought leadership webinars for Cognizant digital services. Partner with sales leadership to generate qualified pipeline.',
    '5-8 years in B2B IT services marketing or corporate communications. Strong experience with CRM platforms, ABM tools, and content syndication.',
    'Join the Cognizant Corporate Marketing practice in Chennai as Digital Marketing Lead. Build high-impact campaigns that demonstrate Cognizant technology expertise to enterprise buyers worldwide.',
    'Group medical insurance, annual appraisal, hybrid work options, higher education support.',
    '2026-03-07T16:00:00Z'::timestamptz,
    'https://careers.cognizant.com/job/digital-marketing-lead-chennai',
    'published',
    false,
    'https://upload.wikimedia.org/wikipedia/commons/thumb/2/22/Cognizant_logo_2022.svg/320px-Cognizant_logo_2022.svg.png'
  ),
  -- 24. [UI Designer] Tata Consultancy Services - Lead UI Designer - TCS BaNCS Financial Products (Chennai)
  (
    '083874aa-0b8d-4b0d-9d68-37d6e0ab4669'::uuid,
    'Tata Consultancy Services',
    'Lead UI Designer - TCS BaNCS Financial Products',
    'UI Designer',
    'Chennai, Tamil Nadu',
    'Onsite',
    'Full time',
    '6-10 years',
    1500000,
    2500000,
    '₹15,00,000 - ₹25,00,000 / yr',
    'INR',
    ARRAY['Banking UI', 'Figma', 'Design Systems', 'Accessibility', 'Responsive Design']::text[],
    'Lead user interface design for the TCS BaNCS core banking and capital markets software suite. Design robust multi-lingual UI systems, compliance dashboards, and customer onboarding portals.',
    '6+ years in UI design, preferably with banking or financial applications. In-depth understanding of UI consistency, design token architecture, and accessibility standards.',
    'TCS Siruseri campus in Chennai—the world largest IT campus—is hiring a Lead UI Designer for its flagship BaNCS financial software division. Help design software that powers central banks and financial institutions globally.',
    'World-class campus amenities, comprehensive health benefits, Tata group employee discounts, retirement schemes, annual bonus.',
    '2026-03-14T10:00:00Z'::timestamptz,
    'https://www.tcs.com/careers/job/lead-ui-designer-chennai',
    'published',
    true,
    'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b1/Tata_Consultancy_Services_Logo.svg/320px-Tata_Consultancy_Services_Logo.svg.png'
  ),
  -- 25. [Frontend Developer] Tata Consultancy Services - Frontend Developer - Digital Banking (Chennai)
  (
    '083874aa-0b8d-4b0d-9d68-37d6e0ab4669'::uuid,
    'Tata Consultancy Services',
    'Frontend Developer - Digital Banking',
    'Frontend Developer',
    'Chennai, Tamil Nadu',
    'Hybrid',
    'Full time',
    '3-6 years',
    900000,
    1600000,
    '₹9,00,000 - ₹16,00,000 / yr',
    'INR',
    ARRAY['React', 'TypeScript', 'REST APIs', 'Redux', 'HTML5/CSS3']::text[],
    'Develop high-security online banking web applications for global financial clients. Write modular, clean React code with unit test coverage, ensuring fast load times and cross-browser reliability.',
    '3-6 years experience in frontend development using React, TypeScript, and Redux. Solid grasp of web security (XSS, CSRF) and responsive web layout techniques.',
    'TCS is hiring a Frontend Developer at our Chennai campus. Build mission-critical digital banking interfaces used by millions of retail and corporate banking customers.',
    'Medical insurance for family, Provident Fund & Gratuity, annual performance bonus, professional upskilling programs.',
    '2026-03-11T14:00:00Z'::timestamptz,
    'https://www.tcs.com/careers/job/frontend-developer-banking-chennai',
    'published',
    false,
    'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b1/Tata_Consultancy_Services_Logo.svg/320px-Tata_Consultancy_Services_Logo.svg.png'
  ),
  -- 26. [HR Recruiter] Tata Consultancy Services - Technical Recruiter - Experience & Campus Hiring (Chennai)
  (
    '083874aa-0b8d-4b0d-9d68-37d6e0ab4669'::uuid,
    'Tata Consultancy Services',
    'Technical Recruiter - Experience & Campus Hiring',
    'HR Recruiter',
    'Chennai, Tamil Nadu',
    'Hybrid',
    'Full time',
    '3-5 years',
    650000,
    1100000,
    '₹6,50,000 - ₹11,00,000 / yr',
    'INR',
    ARRAY['Campus Recruitment', 'Interview Coordination', 'Vendor Management', 'HR Operations', 'Screening']::text[],
    'Coordinate engineering campus placement drives across premier universities in Tamil Nadu and manage lateral hiring for Chennai development centers. Schedule interview panels, administer coding assessments, and handle offer rollouts.',
    '3-5 years in HR recruitment or campus hiring operations. Excellent organizational, scheduling, and interpersonal communication skills.',
    'Tata Consultancy Services is seeking a Technical Recruiter in Chennai to manage university hiring and lateral onboarding for our massive technology delivery centers.',
    'Corporate health insurance, annual bonuses, sports and gymnasium access, career mobility opportunities.',
    '2026-03-09T11:00:00Z'::timestamptz,
    'https://www.tcs.com/careers/job/technical-recruiter-chennai',
    'published',
    false,
    'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b1/Tata_Consultancy_Services_Logo.svg/320px-Tata_Consultancy_Services_Logo.svg.png'
  ),
  -- 27. [Graphic Design] Tata Consultancy Services - Graphic Design Specialist - Corporate Communications (Chennai)
  (
    '083874aa-0b8d-4b0d-9d68-37d6e0ab4669'::uuid,
    'Tata Consultancy Services',
    'Graphic Design Specialist - Corporate Communications',
    'Graphic Design',
    'Chennai, Tamil Nadu',
    'Hybrid',
    'Full time',
    '3-5 years',
    700000,
    1200000,
    '₹7,00,000 - ₹12,00,000 / yr',
    'INR',
    ARRAY['Corporate Branding', 'Adobe InDesign', 'Photoshop', 'Illustrator', 'Infographics']::text[],
    'Design client proposal collateral, annual report graphics, corporate sustainability brochures, and interactive infographics for TCS global leadership. Ensure adherence to Tata brand standards.',
    '3-5 years experience in graphic design and corporate publications. High proficiency in Adobe InDesign, Illustrator, and Photoshop. Excellent sense of typography and page composition.',
    'Join the TCS Global Marketing & Communications studio in Chennai. Produce prestigious corporate design assets for top global corporate events, client summits, and annual publications.',
    'Health insurance, annual performance incentives, campus transport, retirement benefits.',
    '2026-03-06T15:30:00Z'::timestamptz,
    'https://www.tcs.com/careers/job/graphic-designer-chennai',
    'published',
    false,
    'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b1/Tata_Consultancy_Services_Logo.svg/320px-Tata_Consultancy_Services_Logo.svg.png'
  ),
  -- 28. [Product Designer] TVS Motor Company - Senior Product Designer - Connected EV Apps (Chennai)
  (
    'a840e071-f515-4426-8533-67275d5ac1f5'::uuid,
    'TVS Motor Company',
    'Senior Product Designer - Connected EV Apps',
    'Product Designer',
    'Chennai, Tamil Nadu',
    'Hybrid',
    'Full time',
    '4-7 years',
    1600000,
    2600000,
    '₹16,00,000 - ₹26,00,000 / yr',
    'INR',
    ARRAY['Connected Vehicle UX', 'Mobile UI', 'Figma', 'IoT Applications', 'Design Thinking']::text[],
    'Design mobile companion applications for TVS electric scooters (TVS iQube, TVS X). Create digital experiences for remote vehicle telemetry, charging station navigation, geofencing, and digital key sharing.',
    '4-7 years experience designing mobile apps, ideally in IoT, mobility, or automotive connected tech. Strong background in Figma, rapid prototyping, and usability testing.',
    'TVS Motor is leading the green transition in two-wheeler personal mobility. We are hiring a Senior Product Designer in Chennai to design next-generation connected vehicle experiences for riders.',
    'Comprehensive medical coverage, discounts on TVS two-wheelers, annual performance bonus, subsidised dining, flexible hybrid schedule.',
    '2026-03-15T11:30:00Z'::timestamptz,
    'https://www.tvsmotor.com/careers/job/senior-product-designer-ev',
    'published',
    true,
    'https://upload.wikimedia.org/wikipedia/commons/thumb/6/63/TVS_Motor_Company_logo.svg/320px-TVS_Motor_Company_logo.svg.png'
  ),
  -- 29. [Motion Designer] TVS Motor Company - Lead Motion Designer - Smart Dashboard HMI (Chennai)
  (
    'a840e071-f515-4426-8533-67275d5ac1f5'::uuid,
    'TVS Motor Company',
    'Lead Motion Designer - Smart Dashboard HMI',
    'Motion Designer',
    'Chennai, Tamil Nadu',
    'Onsite',
    'Full time',
    '5-8 years',
    1500000,
    2400000,
    '₹15,00,000 - ₹24,00,000 / yr',
    'INR',
    ARRAY['After Effects', 'HMI Animation', 'Lottie', 'Digital Gauges', 'Micro-interactions']::text[],
    'Design dynamic cluster animations, vehicle startup sequences, regenerative braking visual feedback, and drive mode transitions for TFT instrument displays on TVS premium electric vehicles.',
    '5+ years experience in motion design for automotive HMI, gaming, or mobile interfaces. Expert in Adobe After Effects, Lottie, and embedded display animation constraints.',
    'TVS Digital Technology Center in Chennai is looking for a Lead Motion Designer. Shape the futuristic animated instrument clusters that riders experience on every journey.',
    'Competitive salary, annual incentives, family medical insurance, employee vehicle purchase benefits, gratuity.',
    '2026-03-12T15:00:00Z'::timestamptz,
    'https://www.tvsmotor.com/careers/job/lead-motion-designer-hmi',
    'published',
    false,
    'https://upload.wikimedia.org/wikipedia/commons/thumb/6/63/TVS_Motor_Company_logo.svg/320px-TVS_Motor_Company_logo.svg.png'
  ),
  -- 30. [Digital Marketing] TVS Motor Company - Digital Marketing Specialist - EV Mobility (Chennai)
  (
    'a840e071-f515-4426-8533-67275d5ac1f5'::uuid,
    'TVS Motor Company',
    'Digital Marketing Specialist - EV Mobility',
    'Digital Marketing',
    'Chennai, Tamil Nadu',
    'Hybrid',
    'Full time',
    '3-6 years',
    1000000,
    1600000,
    '₹10,00,000 - ₹16,00,000 / yr',
    'INR',
    ARRAY['Social Media Marketing', 'Google Ads', 'Content Marketing', 'EV Branding', 'Influencer Campaigns']::text[],
    'Manage digital launch campaigns, influencer partnerships, and test-ride booking funnels for TVS electric vehicles. Analyze lead acquisition metrics and optimize digital ad spend across social and search platforms.',
    '3-6 years experience in digital brand marketing, preferably in automotive, consumer durables, or tech products. Strong analytical and creative communication skills.',
    'TVS Motor is seeking a Digital Marketing Specialist in Chennai to drive digital consumer awareness and test-ride bookings for our rapidly expanding lineup of electric scooters and motorcycles.',
    'Health insurance, annual performance incentives, hybrid work schedule, employee vehicle schemes.',
    '2026-03-09T13:00:00Z'::timestamptz,
    'https://www.tvsmotor.com/careers/job/digital-marketing-specialist-ev',
    'published',
    false,
    'https://upload.wikimedia.org/wikipedia/commons/thumb/6/63/TVS_Motor_Company_logo.svg/320px-TVS_Motor_Company_logo.svg.png'
  ),
  -- 31. [UI Designer] Ashok Leyland - UI/UX Designer - Connected Vehicle Fleet Platforms (Chennai)
  (
    '61204e34-1c23-4b6f-bb15-a1784d60b6b1'::uuid,
    'Ashok Leyland',
    'UI/UX Designer - Connected Vehicle Fleet Platforms',
    'UI Designer',
    'Chennai, Tamil Nadu',
    'Onsite',
    'Full time',
    '3-6 years',
    1000000,
    1700000,
    '₹10,00,000 - ₹17,00,000 / yr',
    'INR',
    ARRAY['Telematics UI', 'Figma', 'Dashboard Design', 'Data Visualization', 'User Flows']::text[],
    'Design intuitive interfaces for the Ashok Leyland i-Alert telematics platform used by commercial fleet operators. Create real-time vehicle tracking dashboards, fuel consumption analytics, and driver behavior scoring screens.',
    '3-6 years in UI/UX design with experience in data-intensive dashboards or IoT telematics. Proficiency in Figma and user-centric dashboard design.',
    'Ashok Leyland is hiring a UI/UX Designer at our Guindy, Chennai headquarters. Build smart fleet telematics tools that help logistics operators track and optimize thousands of commercial vehicles across India.',
    'Corporate health insurance, annual bonus, subsidized executive dining, gratuity, provident fund.',
    '2026-03-13T10:30:00Z'::timestamptz,
    'https://www.ashokleyland.com/careers/job/ui-ux-designer-telematics',
    'published',
    false,
    'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d4/Ashok_Leyland_logo.svg/320px-Ashok_Leyland_logo.svg.png'
  ),
  -- 32. [HR Recruiter] Ashok Leyland - HR Specialist - Corporate Talent Acquisition (Chennai)
  (
    '61204e34-1c23-4b6f-bb15-a1784d60b6b1'::uuid,
    'Ashok Leyland',
    'HR Specialist - Corporate Talent Acquisition',
    'HR Recruiter',
    'Chennai, Tamil Nadu',
    'Onsite',
    'Full time',
    '3-5 years',
    700000,
    1200000,
    '₹7,00,000 - ₹12,00,000 / yr',
    'INR',
    ARRAY['Manufacturing Recruitment', 'Executive Search', 'Talent Sourcing', 'Interviewing', 'Onboarding']::text[],
    'Lead recruitment for engineering R&D, digital solutions, and supply chain management at Ashok Leyland corporate office. Oversee interview panel scheduling, candidate assessment, and seamless new-hire onboarding.',
    '3-5 years experience in corporate recruitment or talent acquisition in automotive/engineering industries. Strong negotiation and candidate engagement abilities.',
    'Join the Human Resources team at Ashok Leyland headquarters in Chennai. Drive talent acquisition for high-impact commercial vehicle engineering and EV design initiatives.',
    'Medical insurance including family, performance bonus, transport allowances, employee welfare programs.',
    '2026-03-08T11:45:00Z'::timestamptz,
    'https://www.ashokleyland.com/careers/job/hr-specialist-talent-chennai',
    'published',
    false,
    'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d4/Ashok_Leyland_logo.svg/320px-Ashok_Leyland_logo.svg.png'
  ),
  -- 33. [Frontend Developer] HCLTech - Senior Frontend Developer - React & Cloud Web Applications (Chennai)
  (
    'd6b8ee7a-3b10-4d9d-afcf-8fce1b2fc936'::uuid,
    'HCLTech',
    'Senior Frontend Developer - React & Cloud Web Applications',
    'Frontend Developer',
    'Chennai, Tamil Nadu',
    'Hybrid',
    'Full time',
    '4-7 years',
    1200000,
    2000000,
    '₹12,00,000 - ₹20,00,000 / yr',
    'INR',
    ARRAY['React', 'TypeScript', 'Node.js', 'Redux', 'Unit Testing']::text[],
    'Develop cloud-native web portals for global healthcare and telecom clients. Architect reusable React components, optimize page performance, and ensure compliance with security and privacy regulations.',
    '4-7 years experience building web applications with React, TypeScript, and modern CSS frameworks. Strong understanding of RESTful microservices and unit testing.',
    'HCLTech is seeking an experienced Senior Frontend Developer at our Sholinganallur campus in Chennai. Join our engineering practice to deliver scalable web solutions for Fortune 500 enterprises.',
    'Group medical insurance, annual performance incentives, transport facilities, continuous learning academies.',
    '2026-03-14T12:00:00Z'::timestamptz,
    'https://www.hcltech.com/careers/job/senior-frontend-developer-chennai',
    'published',
    false,
    'https://upload.wikimedia.org/wikipedia/commons/thumb/9/95/HCL_Technologies_logo.svg/320px-HCL_Technologies_logo.svg.png'
  ),
  -- 34. [HR Recruiter] HCLTech - Technical Recruiter - Engineering & R&D Services (Chennai)
  (
    'd6b8ee7a-3b10-4d9d-afcf-8fce1b2fc936'::uuid,
    'HCLTech',
    'Technical Recruiter - Engineering & R&D Services',
    'HR Recruiter',
    'Chennai, Tamil Nadu',
    'Hybrid',
    'Full time',
    '3-6 years',
    750000,
    1300000,
    '₹7,50,000 - ₹13,00,000 / yr',
    'INR',
    ARRAY['R&D Recruiting', 'Technical Sourcing', 'LinkedIn Recruiter', 'Offer Negotiation', 'Candidate Care']::text[],
    'Source and recruit skilled engineers for HCLTech Engineering and R&D Services (ERS). Screen candidate profiles, coordinate with hiring managers, and deliver a smooth candidate journey.',
    '3-6 years experience in technical talent acquisition in IT services. Strong proficiency with applicant tracking systems and sourcing portals.',
    'HCLTech is looking for a Technical Recruiter in Chennai to spearhead talent sourcing for our engineering services and embedded software practices.',
    'Medical insurance, annual performance bonus, hybrid work model, employee wellness initiatives.',
    '2026-03-10T16:15:00Z'::timestamptz,
    'https://www.hcltech.com/careers/job/technical-recruiter-chennai',
    'published',
    false,
    'https://upload.wikimedia.org/wikipedia/commons/thumb/9/95/HCL_Technologies_logo.svg/320px-HCL_Technologies_logo.svg.png'
  ),
  -- 35. [Product Designer] Ramco Systems - Product Designer - Enterprise ERP & Aviation Software (Chennai)
  (
    '4392a8e9-4b6d-433a-902c-b1ffeec9e0b7'::uuid,
    'Ramco Systems',
    'Product Designer - Enterprise ERP & Aviation Software',
    'Product Designer',
    'Chennai, Tamil Nadu',
    'Onsite',
    'Full time',
    '4-7 years',
    1200000,
    1900000,
    '₹12,00,000 - ₹19,00,000 / yr',
    'INR',
    ARRAY['Enterprise UX', 'Figma', 'Complex Data Grids', 'Prototyping', 'User Research']::text[],
    'Design next-generation interfaces for Ramco Aviation M&E and Global Payroll software. Simplify dense operational data grids, aircraft maintenance tracking logs, and automated compliance workflows.',
    '4-7 years experience designing complex enterprise software, aviation tools, or ERP suites. Strong grasp of information architecture and visual design in Figma.',
    'Ramco Systems is hiring a Product Designer at our Chennai campus in Taramani. Help transform complex aviation maintenance and enterprise payroll into intuitive, modern digital experiences.',
    'Comprehensive healthcare coverage, annual performance bonus, subsidized dining on campus, retirement benefits.',
    '2026-03-11T13:45:00Z'::timestamptz,
    'https://www.ramco.com/careers/job/product-designer-aviation-chennai',
    'published',
    false,
    'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e0/Ramco_Systems_logo.svg/320px-Ramco_Systems_logo.svg.png'
  ),
  -- 36. [Frontend Developer] Cognizant India - Senior Frontend Developer - React & Cloud (Coimbatore)
  (
    'c2567649-fe59-4405-8eec-ed6996a37990'::uuid,
    'Cognizant India',
    'Senior Frontend Developer - React & Cloud',
    'Frontend Developer',
    'Coimbatore, Tamil Nadu',
    'Hybrid',
    'Full time',
    '3-6 years',
    900000,
    1500000,
    '₹9,00,000 - ₹15,00,000 / yr',
    'INR',
    ARRAY['React', 'JavaScript', 'HTML5', 'CSS3', 'Git']::text[],
    'Develop customer-facing web applications for international retail and healthcare clients. Build responsive, accessible React components and integrate with cloud microservices.',
    '3-6 years experience developing web applications with React and JavaScript. Familiarity with REST APIs, state management, and Git workflows.',
    'Cognizant is hiring a Senior Frontend Developer at our CHIL SEZ campus in Coimbatore. Work on global enterprise applications in a vibrant, collaborative engineering environment.',
    'Health insurance, annual performance incentives, campus transport, professional training programs.',
    '2026-03-13T10:00:00Z'::timestamptz,
    'https://careers.cognizant.com/job/frontend-developer-coimbatore',
    'published',
    false,
    'https://upload.wikimedia.org/wikipedia/commons/thumb/2/22/Cognizant_logo_2022.svg/320px-Cognizant_logo_2022.svg.png'
  ),
  -- 37. [UI Designer] Cognizant India - UI Designer - Healthcare Practice (Coimbatore)
  (
    'c2567649-fe59-4405-8eec-ed6996a37990'::uuid,
    'Cognizant India',
    'UI Designer - Healthcare Practice',
    'UI Designer',
    'Coimbatore, Tamil Nadu',
    'Hybrid',
    'Full time',
    '3-5 years',
    800000,
    1300000,
    '₹8,00,000 - ₹13,00,000 / yr',
    'INR',
    ARRAY['Figma', 'UI Design', 'Design Systems', 'Medical App UI', 'Accessibility']::text[],
    'Design clean, intuitive user interfaces for healthcare portals, patient record systems, and pharmacy management tools. Ensure compliance with healthcare accessibility guidelines.',
    '3-5 years UI design experience. Proficient in Figma and Adobe Creative Cloud. Good understanding of design systems and responsive web principles.',
    'Join Cognizant Healthcare Technology practice at our Coimbatore center. Design accessible, empathetic user interfaces that improve healthcare delivery worldwide.',
    'Comprehensive health cover, annual increments, transport facility, certification sponsorship.',
    '2026-03-10T15:00:00Z'::timestamptz,
    'https://careers.cognizant.com/job/ui-designer-coimbatore',
    'published',
    false,
    'https://upload.wikimedia.org/wikipedia/commons/thumb/2/22/Cognizant_logo_2022.svg/320px-Cognizant_logo_2022.svg.png'
  ),
  -- 38. [HR Recruiter] Cognizant India - Technical Recruiter - IT Delivery Center (Coimbatore)
  (
    'c2567649-fe59-4405-8eec-ed6996a37990'::uuid,
    'Cognizant India',
    'Technical Recruiter - IT Delivery Center',
    'HR Recruiter',
    'Coimbatore, Tamil Nadu',
    'Hybrid',
    'Full time',
    '2-5 years',
    600000,
    1050000,
    '₹6,00,000 - ₹10,50,000 / yr',
    'INR',
    ARRAY['Talent Sourcing', 'IT Recruitment', 'Screening', 'Campus Recruitment', 'Interview Coordination']::text[],
    'Manage talent sourcing and hiring operations for Cognizant Coimbatore delivery center. Conduct initial phone screens, schedule technical interviews, and coordinate campus placement drives.',
    '2-5 years of technical recruiting experience. Strong communication skills and familiarity with applicant tracking systems.',
    'Cognizant is expanding its talent acquisition team at its major tech hub in Coimbatore. Connect talented engineers with exciting global software projects.',
    'Medical insurance, annual performance bonus, campus amenities, career growth paths.',
    '2026-03-08T11:00:00Z'::timestamptz,
    'https://careers.cognizant.com/job/technical-recruiter-coimbatore',
    'published',
    false,
    'https://upload.wikimedia.org/wikipedia/commons/thumb/2/22/Cognizant_logo_2022.svg/320px-Cognizant_logo_2022.svg.png'
  ),
  -- 39. [UX Designer] Tata Consultancy Services - UX Designer - Enterprise Systems (Coimbatore)
  (
    '083874aa-0b8d-4b0d-9d68-37d6e0ab4669'::uuid,
    'Tata Consultancy Services',
    'UX Designer - Enterprise Systems',
    'UX Designer',
    'Coimbatore, Tamil Nadu',
    'Onsite',
    'Full time',
    '3-6 years',
    850000,
    1400000,
    '₹8,50,000 - ₹14,00,000 / yr',
    'INR',
    ARRAY['User Journey Mapping', 'Wireframing', 'Figma', 'Usability Audits', 'Persona Creation']::text[],
    'Conduct user research, design task flows, and create wireframes for enterprise cloud management applications. Collaborate with global business analysts to streamline user workflows.',
    '3-6 years experience in UX design and research. Strong portfolio showcasing user journey maps, wireframes, and usability audit reports.',
    'TCS Coimbatore Development Center in Peelamedu is hiring a UX Designer. Design thoughtful, user-friendly digital tools for global manufacturing and retail clients.',
    'Group medical insurance, Provident Fund, annual performance bonus, sports facilities.',
    '2026-03-12T14:00:00Z'::timestamptz,
    'https://www.tcs.com/careers/job/ux-designer-coimbatore',
    'published',
    false,
    'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b1/Tata_Consultancy_Services_Logo.svg/320px-Tata_Consultancy_Services_Logo.svg.png'
  ),
  -- 40. [Frontend Developer] Tata Consultancy Services - Frontend Engineer - Modern Web Technologies (Coimbatore)
  (
    '083874aa-0b8d-4b0d-9d68-37d6e0ab4669'::uuid,
    'Tata Consultancy Services',
    'Frontend Engineer - Modern Web Technologies',
    'Frontend Developer',
    'Coimbatore, Tamil Nadu',
    'Hybrid',
    'Full time',
    '2-5 years',
    750000,
    1250000,
    '₹7,50,000 - ₹12,50,000 / yr',
    'INR',
    ARRAY['React', 'TypeScript', 'CSS3', 'REST APIs', 'Webpack']::text[],
    'Develop responsive, accessible web pages using React and TypeScript. Work in agile squads to implement new features, fix defects, and maintain high code quality.',
    '2-5 years experience developing frontend applications with React. Good knowledge of modern JavaScript, CSS, and version control using Git.',
    'TCS is seeking a motivated Frontend Engineer for its Coimbatore center. Work on cutting-edge digital projects for top international clients.',
    'Corporate health benefits, annual increments, transport facility, continuous learning opportunities.',
    '2026-03-09T10:15:00Z'::timestamptz,
    'https://www.tcs.com/careers/job/frontend-engineer-coimbatore',
    'published',
    false,
    'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b1/Tata_Consultancy_Services_Logo.svg/320px-Tata_Consultancy_Services_Logo.svg.png'
  ),
  -- 41. [HR Recruiter] Tata Consultancy Services - HR Executive - Regional Talent Sourcing (Coimbatore)
  (
    '083874aa-0b8d-4b0d-9d68-37d6e0ab4669'::uuid,
    'Tata Consultancy Services',
    'HR Executive - Regional Talent Sourcing',
    'HR Recruiter',
    'Coimbatore, Tamil Nadu',
    'Hybrid',
    'Full time',
    '2-4 years',
    550000,
    900000,
    '₹5,50,000 - ₹9,00,000 / yr',
    'INR',
    ARRAY['Campus Sourcing', 'Candidate Onboarding', 'ATS Management', 'Screening', 'Documentation']::text[],
    'Support campus and lateral hiring operations across Western Tamil Nadu colleges. Track candidate pipelines in the ATS, coordinate interview logistics, and facilitate onboarding documentation.',
    '2-4 years experience in HR talent acquisition or recruitment coordination. Excellent organizational and interpersonal skills.',
    'Join the TCS Human Resources team at our Coimbatore Tidel Park campus. Help identify and onboard promising engineering talent for regional delivery projects.',
    'Medical coverage, retirement schemes, annual bonus, sports and cultural events.',
    '2026-03-07T12:30:00Z'::timestamptz,
    'https://www.tcs.com/careers/job/hr-executive-coimbatore',
    'published',
    false,
    'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b1/Tata_Consultancy_Services_Logo.svg/320px-Tata_Consultancy_Services_Logo.svg.png'
  ),
  -- 42. [Frontend Developer] Infosys - Senior Systems Engineer - Frontend (React/TypeScript) (Coimbatore)
  (
    '87b0b818-7c37-41c7-9536-f5fb99805d80'::uuid,
    'Infosys',
    'Senior Systems Engineer - Frontend (React/TypeScript)',
    'Frontend Developer',
    'Coimbatore, Tamil Nadu',
    'Hybrid',
    'Full time',
    '3-5 years',
    800000,
    1350000,
    '₹8,00,000 - ₹13,50,000 / yr',
    'INR',
    ARRAY['React', 'TypeScript', 'JavaScript ES6', 'Bootstrap', 'Jest']::text[],
    'Develop and maintain enterprise web applications for Fortune 500 financial and telecom clients. Write clean, modular, and unit-tested React components adhering to coding standards.',
    '3-5 years experience developing web applications with React, TypeScript, and HTML5. Familiarity with RESTful APIs, Git, and automated testing tools.',
    'Infosys Coimbatore Center is hiring a Senior Systems Engineer - Frontend. Work with global clients on digital transformation initiatives while enjoying a great work-life balance in Coimbatore.',
    'Health insurance, annual appraisal, Provident Fund, higher education programs, sports complex.',
    '2026-03-14T15:30:00Z'::timestamptz,
    'https://careers.infosys.com/job/senior-systems-engineer-frontend-coimbatore',
    'published',
    false,
    'https://upload.wikimedia.org/wikipedia/commons/9/95/Infosys_logo.svg'
  ),
  -- 43. [Digital Marketing] Infosys - Digital Marketing Specialist - Regional Growth (Coimbatore)
  (
    '87b0b818-7c37-41c7-9536-f5fb99805d80'::uuid,
    'Infosys',
    'Digital Marketing Specialist - Regional Growth',
    'Digital Marketing',
    'Coimbatore, Tamil Nadu',
    'Hybrid',
    'Full time',
    '3-5 years',
    700000,
    1150000,
    '₹7,00,000 - ₹11,50,000 / yr',
    'INR',
    ARRAY['Email Marketing', 'Google Analytics', 'Campaign Management', 'SEO Basics', 'Content Layout']::text[],
    'Coordinate email nurture campaigns, webinar execution, and analytics reporting for Infosys regional digital practices. Monitor engagement metrics and optimize marketing funnels.',
    '3-5 years experience in digital marketing or corporate communications. Strong analytical skills and familiarity with marketing automation platforms.',
    'Infosys is seeking a Digital Marketing Specialist in Coimbatore. Help showcase Infosys technology expertise to regional and global enterprise clients through effective digital campaigns.',
    'Corporate health cover, annual performance bonus, transport facility, continuous learning academies.',
    '2026-03-11T16:00:00Z'::timestamptz,
    'https://careers.infosys.com/job/digital-marketing-specialist-coimbatore',
    'published',
    false,
    'https://upload.wikimedia.org/wikipedia/commons/9/95/Infosys_logo.svg'
  ),
  -- 44. [Product Designer] Zoho Corporation - Product Designer - Business Productivity Apps (Coimbatore)
  (
    'b16d2f7d-a481-4986-9c91-be2325734ac7'::uuid,
    'Zoho Corporation',
    'Product Designer - Business Productivity Apps',
    'Product Designer',
    'Coimbatore, Tamil Nadu',
    'Onsite',
    'Full time',
    '3-6 years',
    1000000,
    1600000,
    '₹10,00,000 - ₹16,00,000 / yr',
    'INR',
    ARRAY['Product Thinking', 'Figma', 'Mobile Design', 'User Workflows', 'Prototyping']::text[],
    'Design intuitive mobile and web interfaces for Zoho productivity and collaboration tools. Partner with engineering squads to turn user feedback into refined, accessible feature releases.',
    '3-6 years experience as a product designer for digital applications. Proficiency in Figma and interactive prototyping. Passion for simple, purposeful software design.',
    'Zoho Coimbatore development center is hiring a Product Designer. Design tools that help businesses and teams collaborate seamlessly from anywhere in the world.',
    'Predictable fixed compensation, complete health coverage, complimentary meals on-site, generous leave policies.',
    '2026-03-15T13:00:00Z'::timestamptz,
    'https://www.zoho.com/careers/job/product-designer-coimbatore',
    'published',
    true,
    'https://upload.wikimedia.org/wikipedia/commons/thumb/6/6d/Zoho_Corporation_2019_logo.svg/320px-Zoho_Corporation_2019_logo.svg.png'
  ),
  -- 45. [Visual Designer] Wipro - Visual Designer - Enterprise Applications (Coimbatore)
  (
    '32a33ef9-eac4-404e-b4b3-83817f71081f'::uuid,
    'Wipro',
    'Visual Designer - Enterprise Applications',
    'Visual Designer',
    'Coimbatore, Tamil Nadu',
    'Hybrid',
    'Full time',
    '3-5 years',
    750000,
    1250000,
    '₹7,50,000 - ₹12,50,000 / yr',
    'INR',
    ARRAY['Visual Design', 'Figma', 'UI Components', 'Graphic Systems', 'Style Guides']::text[],
    'Create visual guidelines, UI mockups, and icon sets for enterprise cloud applications. Collaborate with UX designers to ensure high visual quality and aesthetic coherence.',
    '3-5 years experience in visual design for software. Expert in Figma, Adobe Illustrator, and visual hierarchy.',
    'Wipro is hiring a Visual Designer at our Coimbatore center. Join our design practice to craft clean, modern digital interfaces for global enterprise clients.',
    'Health insurance, annual performance incentives, hybrid work schedule, sports access.',
    '2026-03-08T10:00:00Z'::timestamptz,
    'https://careers.wipro.com/job/visual-designer-coimbatore',
    'published',
    false,
    'https://upload.wikimedia.org/wikipedia/commons/a/a0/Wipro_Primary_Logo_Color_RGB.svg'
  ),
  -- 46. [Frontend Developer] Tata Consultancy Services - Frontend Developer - Cloud Enterprise Platforms (Trichy)
  (
    '083874aa-0b8d-4b0d-9d68-37d6e0ab4669'::uuid,
    'Tata Consultancy Services',
    'Frontend Developer - Cloud Enterprise Platforms',
    'Frontend Developer',
    'Trichy, Tamil Nadu',
    'Hybrid',
    'Full time',
    '3-5 years',
    750000,
    1200000,
    '₹7,50,000 - ₹12,00,000 / yr',
    'INR',
    ARRAY['React', 'JavaScript', 'HTML5', 'CSS3', 'REST APIs']::text[],
    'Develop scalable frontend modules for enterprise cloud platforms. Maintain high coding standards, write unit tests, and work with backend developers on API integration.',
    '3-5 years experience developing web applications with React and modern JavaScript. Good understanding of responsive design, state management, and Git.',
    'TCS Trichy Development Center is looking for an experienced Frontend Developer. Build modern web applications for global enterprise clients while based in Tiruchirappalli.',
    'Corporate health insurance, annual performance bonus, transport facility, retirement benefits.',
    '2026-03-12T11:30:00Z'::timestamptz,
    'https://www.tcs.com/careers/job/frontend-developer-trichy',
    'published',
    false,
    'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b1/Tata_Consultancy_Services_Logo.svg/320px-Tata_Consultancy_Services_Logo.svg.png'
  ),
  -- 47. [HR Recruiter] Tata Consultancy Services - Technical Recruiter - Regional Sourcing & Campus (Trichy)
  (
    '083874aa-0b8d-4b0d-9d68-37d6e0ab4669'::uuid,
    'Tata Consultancy Services',
    'Technical Recruiter - Regional Sourcing & Campus',
    'HR Recruiter',
    'Trichy, Tamil Nadu',
    'Onsite',
    'Full time',
    '2-5 years',
    550000,
    950000,
    '₹5,50,000 - ₹9,50,000 / yr',
    'INR',
    ARRAY['Campus Hiring', 'Interview Panels', 'Talent Sourcing', 'Offer Management', 'HR Analytics']::text[],
    'Drive campus recruitment drives and entry-level talent acquisition across engineering colleges in Central Tamil Nadu (NIT Trichy, regional universities). Coordinate interview schedules and offer documentation.',
    '2-5 years experience in campus recruitment or talent sourcing. Strong interpersonal communication and operational efficiency.',
    'TCS is hiring a Technical Recruiter at our Trichy center to lead university engagement and talent onboarding for our expanding regional delivery centers.',
    'Group medical insurance, annual bonus, access to sports facilities, career mobility opportunities.',
    '2026-03-10T09:30:00Z'::timestamptz,
    'https://www.tcs.com/careers/job/technical-recruiter-trichy',
    'published',
    false,
    'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b1/Tata_Consultancy_Services_Logo.svg/320px-Tata_Consultancy_Services_Logo.svg.png'
  ),
  -- 48. [UI Designer] Cognizant India - UI/UX Designer - Digital Modernization (Trichy)
  (
    'c2567649-fe59-4405-8eec-ed6996a37990'::uuid,
    'Cognizant India',
    'UI/UX Designer - Digital Modernization',
    'UI Designer',
    'Trichy, Tamil Nadu',
    'Hybrid',
    'Full time',
    '2-5 years',
    700000,
    1150000,
    '₹7,00,000 - ₹11,50,000 / yr',
    'INR',
    ARRAY['Figma', 'Wireframing', 'UI Design', 'User Flows', 'Prototyping']::text[],
    'Design intuitive UI wireframes, user task flows, and interactive mockups for digital modernization projects. Partner with technical teams to ensure accurate design implementation.',
    '2-5 years experience in UI/UX design. Proficient in Figma, wireframing, and component design.',
    'Cognizant is hiring a UI/UX Designer at its Trichy delivery unit. Work with experienced engineering squads to modernize enterprise applications for international clients.',
    'Medical insurance covering dependents, annual increments, flexible working hours, training programs.',
    '2026-03-14T12:45:00Z'::timestamptz,
    'https://careers.cognizant.com/job/ui-ux-designer-trichy',
    'published',
    false,
    'https://upload.wikimedia.org/wikipedia/commons/thumb/2/22/Cognizant_logo_2022.svg/320px-Cognizant_logo_2022.svg.png'
  ),
  -- 49. [Frontend Developer] Zoho Corporation - Frontend Developer - Web Platforms & Tools (Trichy)
  (
    'b16d2f7d-a481-4986-9c91-be2325734ac7'::uuid,
    'Zoho Corporation',
    'Frontend Developer - Web Platforms & Tools',
    'Frontend Developer',
    'Trichy, Tamil Nadu',
    'Onsite',
    'Full time',
    '2-5 years',
    800000,
    1300000,
    '₹8,00,000 - ₹13,00,000 / yr',
    'INR',
    ARRAY['JavaScript', 'React', 'HTML5', 'CSS3', 'Single Page Apps']::text[],
    'Build responsive single-page web applications and interactive widgets for Zoho cloud products. Optimize front-end code for minimal latency and high client-side responsiveness.',
    '2-5 years of strong JavaScript and React experience. Passion for clean code, problem-solving, and browser performance optimization.',
    'Zoho Corporation is hiring a Frontend Developer at our regional development center in Trichy. Join our product engineering practice and build software that scales to millions of users worldwide.',
    'Competitive fixed compensation, full health coverage, delicious on-site meals, peaceful work environment, annual profit sharing.',
    '2026-03-15T16:00:00Z'::timestamptz,
    'https://www.zoho.com/careers/job/frontend-developer-trichy',
    'published',
    true,
    'https://upload.wikimedia.org/wikipedia/commons/thumb/6/6d/Zoho_Corporation_2019_logo.svg/320px-Zoho_Corporation_2019_logo.svg.png'
  ),
  -- 50. [Graphic Design] Infosys - Graphic Design & Communications Specialist (Trichy)
  (
    '87b0b818-7c37-41c7-9536-f5fb99805d80'::uuid,
    'Infosys',
    'Graphic Design & Communications Specialist',
    'Graphic Design',
    'Trichy, Tamil Nadu',
    'Hybrid',
    'Full time',
    '2-4 years',
    650000,
    1050000,
    '₹6,50,000 - ₹10,50,000 / yr',
    'INR',
    ARRAY['Adobe Creative Cloud', 'Infographics', 'Presentation Design', 'Vector Art', 'Branding']::text[],
    'Create business presentation decks, digital collateral, infographic summaries, and client proposal graphics for enterprise consulting teams. Ensure brand consistency across all visual assets.',
    '2-4 years experience in graphic design and digital presentation creation. Skilled in Adobe Illustrator, Photoshop, and PowerPoint.',
    'Infosys is seeking a Graphic Design & Communications Specialist based in Trichy. Work with global business consulting teams to produce clear, impactful visual presentations and documents.',
    'Health insurance, annual performance incentives, transport support, higher education sponsorship.',
    '2026-03-09T14:30:00Z'::timestamptz,
    'https://careers.infosys.com/job/graphic-designer-trichy',
    'published',
    false,
    'https://upload.wikimedia.org/wikipedia/commons/9/95/Infosys_logo.svg'
  );
