-- HireIn AI: 50 Real Karnataka Job Openings Seed Script
-- Cities: Bengaluru (40), Mysuru (5), Mangalore (5)
-- Categories (10): Graphic Design, UI Designer, UX Designer, Product Designer, Motion Designer,
--                  Brand Designer, Visual Designer, Digital Marketing, Frontend Developer, HR Recruiter
-- All companies exist in public.companies and have active hiring presence in Karnataka.

alter table public.jobs add column if not exists source_url text;

insert into public.jobs (
  company_id,
  company,
  title,
  category,
  location,
  work_mode,
  employment_type,
  experience,
  salary_min,
  salary_max,
  salary,
  currency,
  skills,
  responsibilities,
  requirements,
  description,
  benefits,
  posted_at,
  source_url,
  status,
  featured,
  logo
)
values
  -- 1. [Graphic Design] Flipkart - Senior Graphic Designer - Brand Campaigns (Bengaluru)
  (
    'f569aa55-4aa4-488c-840b-8962f282294e'::uuid,
    'Flipkart',
    'Senior Graphic Designer - Brand Campaigns',
    'Graphic Design',
    'Bengaluru, Karnataka',
    'Hybrid',
    'Full time',
    '3-6 years',
    1000000,
    1600000,
    '₹10,00,000 - ₹16,00,000 / yr',
    'INR',
    ARRAY['Photoshop', 'Illustrator', 'Visual Storytelling', 'Campaign Design', 'Typography']::text[],
    'Lead concept development and high-impact visual design for Flipkart seasonal mega-sales, brand launches, and omnichannel marketing initiatives. Partner with copywriters, art directors, and brand leads to create cohesive design narratives across digital and print media.',
    '3+ years of professional graphic design experience at a consumer brand or leading creative agency. Mastery of Adobe Creative Suite (Photoshop, Illustrator, InDesign). Strong portfolio showcasing campaign visuals, editorial design, and typography hierarchy.',
    'Flipkart is seeking an experienced Senior Graphic Designer to elevate our visual marketing campaigns. You will conceptualize and deliver creative assets that reach over 400 million registered customers across India.',
    'Comprehensive medical insurance (covering family), annual performance bonus, mobile & internet reimbursement, wellness allowances, Flipkart employee discounts, flexible hybrid work policy.',
    '2026-03-12T10:00:00Z'::timestamptz,
    'https://www.flipkartcareers.com/job/senior-graphic-designer-campaigns',
    'published',
    true,
    'https://upload.wikimedia.org/wikipedia/en/thumb/7/7a/Flipkart_logo.svg/320px-Flipkart_logo.svg.png'
  ),
  -- 2. [Graphic Design] Swiggy - Graphic Designer - Instamart Creative Studio (Bengaluru)
  (
    'b57f1a24-89d5-4099-81c0-9dc0b66ef459'::uuid,
    'Swiggy',
    'Graphic Designer - Instamart Creative Studio',
    'Graphic Design',
    'Bengaluru, Karnataka',
    'Onsite',
    'Full time',
    '2-5 years',
    800000,
    1400000,
    '₹8,00,000 - ₹14,00,000 / yr',
    'INR',
    ARRAY['Photoshop', 'Illustrator', 'Digital Illustration', 'Ad Creatives', 'Social Media Design']::text[],
    'Create engaging digital banners, in-app promotional graphics, and push notification visual creatives for Swiggy Instamart. Maintain brand consistency, turn rapid marketing briefs into punchy visual concepts, and experiment with visual formats to maximize click-through rates.',
    '2-5 years experience producing fast-paced marketing and social media graphics. Exceptional proficiency in Adobe Illustrator and Photoshop. Ability to create original vector illustrations and custom typography lockups under tight turnaround times.',
    'Join the Swiggy Instamart Creative Studio at our Bengaluru headquarters. You will design visual touchpoints that entice millions of quick-commerce shoppers every day with witty, vibrant, and appetizing creative executions.',
    'Group medical and term life insurance, daily catered lunches at HQ, Swiggy One premium subscription, mental wellness support, fitness reimbursements.',
    '2026-03-14T09:30:00Z'::timestamptz,
    'https://swiggy.freshteam.com/jobs/graphic-designer-instamart',
    'published',
    false,
    'https://upload.wikimedia.org/wikipedia/en/thumb/1/12/Swiggy_logo.svg/320px-Swiggy_logo.svg.png'
  ),
  -- 3. [Graphic Design] Myntra - Lead Graphic Designer - Fashion Content (Bengaluru)
  (
    '5101f225-e0d5-459d-928e-6bdc68fb8e23'::uuid,
    'Myntra',
    'Lead Graphic Designer - Fashion Content',
    'Graphic Design',
    'Bengaluru, Karnataka',
    'Hybrid',
    'Full time',
    '5-8 years',
    1400000,
    2200000,
    '₹14,00,000 - ₹22,00,000 / yr',
    'INR',
    ARRAY['Creative Direction', 'Photoshop', 'InDesign', 'Editorial Layout', 'Fashion Graphics']::text[],
    'Direct the visual styling, editorial layouts, and digital catalog designs for premium fashion brands on Myntra. Guide junior graphic artists, review creative submissions, and partner with photography teams to establish seasonal lookbooks and trend reports.',
    '5+ years of experience in fashion, lifestyle, or luxury e-commerce graphic design. Deep understanding of fashion aesthetics, color palettes, and editorial typography. Strong portfolio demonstrating artistic direction and publication layout.',
    'Myntra is hiring a Lead Graphic Designer to define the aesthetic presentation of our flagship fashion festivals and global brand partnerships. This role blends editorial artistry with high-conversion e-commerce visuals.',
    'Subsidized health insurance, generous employee wardrobe discounts, hybrid work schedule, wellness stipend, annual learning and skill development grant.',
    '2026-03-10T11:15:00Z'::timestamptz,
    'https://careers.myntra.com/jobs/lead-graphic-designer-fashion',
    'published',
    true,
    'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d5/Myntra_logo.png/320px-Myntra_logo.png'
  ),
  -- 4. [Graphic Design] BigBasket - Graphic Designer - Growth & Performance (Bengaluru)
  (
    '40393f4e-a82d-4606-8e07-b5ea63fd592d'::uuid,
    'BigBasket',
    'Graphic Designer - Growth & Performance',
    'Graphic Design',
    'Bengaluru, Karnataka',
    'Onsite',
    'Full time',
    '2-4 years',
    700000,
    1100000,
    '₹7,00,000 - ₹11,00,000 / yr',
    'INR',
    ARRAY['Graphic Design', 'Figma', 'Banner Design', 'Performance Marketing', 'Canva']::text[],
    'Produce performance marketing banner suites across Google Display, Meta, and affiliate networks. A/B test creative variations (copy placement, imagery, badges) and analyze creative performance dashboards to iterate on high-converting ads.',
    '2-4 years of experience crafting performance marketing creatives for consumer brands. Proficiency in Figma and Adobe Photoshop. Solid grasp of conversion-centric layout and visual hierarchy.',
    'BigBasket is expanding its digital growth creative unit in Bengaluru. We need a detail-oriented Graphic Designer who understands how visual elements directly drive user acquisition and basket additions.',
    'Health insurance covering dependents, free grocery delivery benefits, provident fund, annual appraisal, structured career progression.',
    '2026-03-16T14:00:00Z'::timestamptz,
    'https://careers.bigbasket.com/job/graphic-designer-growth',
    'published',
    false,
    'https://upload.wikimedia.org/wikipedia/en/thumb/0/07/Bigbasket_Logo.svg/320px-Bigbasket_Logo.svg.png'
  ),
  -- 5. [Graphic Design] Infosys - Graphic Design Specialist (Mangalore)
  (
    '87b0b818-7c37-41c7-9536-f5fb99805d80'::uuid,
    'Infosys',
    'Graphic Design Specialist',
    'Graphic Design',
    'Mangalore, Karnataka',
    'Hybrid',
    'Full time',
    '3-5 years',
    750000,
    1200000,
    '₹7,50,000 - ₹12,00,000 / yr',
    'INR',
    ARRAY['Adobe Creative Cloud', 'Infographics', 'Corporate Branding', 'Vector Illustration', 'PowerPoint']::text[],
    'Design enterprise communication materials, client proposal collateral, whitepapers, infographic diagrams, and corporate presentation templates for global Fortune 500 clients. Ensure global brand guidelines are met across all delivered assets.',
    'Bachelor degree in Fine Arts, Design, or related field with 3-5 years of graphic design experience in IT or corporate environments. Expertise in Adobe Illustrator, Photoshop, and advanced corporate presentation design.',
    'Infosys is looking for a talented Graphic Design Specialist based at our picturesque Mangalore SEZ campus. You will collaborate with global marketing and consulting teams to produce world-class enterprise collateral.',
    'Campus transport facilities, comprehensive group health insurance, Provident Fund & Gratuity, annual performance bonus, higher education sponsorship opportunities.',
    '2026-03-08T09:00:00Z'::timestamptz,
    'https://careers.infosys.com/job/graphic-design-specialist-mangalore',
    'published',
    false,
    'https://upload.wikimedia.org/wikipedia/commons/9/95/Infosys_logo.svg'
  ),
  -- 6. [UI Designer] Razorpay - Senior UI Designer - Payment Systems (Bengaluru)
  (
    '7ad5299e-facc-4337-b106-461f2750161c'::uuid,
    'Razorpay',
    'Senior UI Designer - Payment Systems',
    'UI Designer',
    'Bengaluru, Karnataka',
    'Hybrid',
    'Full time',
    '4-7 years',
    1600000,
    2600000,
    '₹16,00,000 - ₹26,00,000 / yr',
    'INR',
    ARRAY['Figma', 'Design Systems', 'Micro-interactions', 'UI Architecture', 'Prototyping']::text[],
    'Craft elegant, pixel-perfect user interfaces for Razorpay Checkout, payment gateways, and developer dashboard surfaces. Own and extend the Razorpay Blade design system, documenting UI tokens, accessibility standards, and responsive web states.',
    '4+ years designing high-volume web and mobile application interfaces. World-class proficiency in Figma, component auto-layout, and interactive prototyping. Deep knowledge of WCAG 2.1 accessibility guidelines.',
    'Razorpay powers payments for over 10 million businesses across India. We are looking for a Senior UI Designer in Bengaluru to craft cohesive, ultra-reliable fintech interfaces that inspire trust in every financial interaction.',
    'Comprehensive medical coverage with zero co-pay, ESOP opportunities, unlimited wellness leave, annual learning budget, home office setup reimbursement.',
    '2026-03-15T12:00:00Z'::timestamptz,
    'https://razorpay.com/jobs/senior-ui-designer-payments',
    'published',
    true,
    'https://upload.wikimedia.org/wikipedia/commons/8/89/Razorpay_logo.svg'
  ),
  -- 7. [UI Designer] PhonePe - UI Designer - Merchant Solutions (Bengaluru)
  (
    'a6faf52b-f50a-4f98-9e03-62ec785d6e38'::uuid,
    'PhonePe',
    'UI Designer - Merchant Solutions',
    'UI Designer',
    'Bengaluru, Karnataka',
    'Onsite',
    'Full time',
    '3-5 years',
    1400000,
    2200000,
    '₹14,00,000 - ₹22,00,000 / yr',
    'INR',
    ARRAY['Figma', 'Mobile UI', 'Material Design', 'Visual Hierarchy', 'Wireframing']::text[],
    'Design frictionless UI flows for the PhonePe Business app used by 35 million offline merchants across India. Create clear visual data visualizations, settlement summaries, soundbox management controls, and QR code tracking screens.',
    '3-5 years of mobile UI design experience for Android and iOS apps. Proven track record of shipping production-grade UI interfaces. Mastery of Figma, layout grids, icon design, and design token integration.',
    'PhonePe is hiring a UI Designer to help empower small merchants and tier-2/3 business owners with intuitive digital financial tools. Join our team at our Bengaluru campus and shape inclusive mobile interfaces.',
    'Medical insurance including parents, gratuity, complimentary office breakfast and lunch, annual bonuses, cab pickup and drop services.',
    '2026-03-11T10:45:00Z'::timestamptz,
    'https://www.phonepe.com/careers/job/ui-designer-merchant',
    'published',
    false,
    'https://upload.wikimedia.org/wikipedia/commons/7/71/PhonePe_Logo.svg'
  ),
  -- 8. [UI Designer] CRED - Staff UI Designer - Core Experience (Bengaluru)
  (
    '7ee4aa16-22ec-4334-b274-e529864e53c8'::uuid,
    'CRED',
    'Staff UI Designer - Core Experience',
    'UI Designer',
    'Bengaluru, Karnataka',
    'Onsite',
    'Full time',
    '6-9 years',
    2500000,
    4000000,
    '₹25,00,000 - ₹40,00,000 / yr',
    'INR',
    ARRAY['Figma', 'Craftsmanship', 'Design Systems', 'Dark Mode UI', 'Typography']::text[],
    'Set the benchmark for visual finesse and sensory design on CRED flagship app surfaces. Obsess over micro-details, tactile feedback, typography scales, dynamic lighting shaders, and bespoke dark-theme interface palettes.',
    '6+ years in visual and UI design with an extraordinary portfolio showcasing immaculate craftsmanship, aesthetic discernment, and innovative interface thinking. Proven leadership in evolving complex mobile design systems.',
    'At CRED, design is not an afterthought—it is the product. We are seeking a Staff UI Designer in Indiranagar, Bengaluru who lives and breathes craft, pushing mobile UI boundaries to deliver delightfully distinct experiences.',
    'Top-tier executive health coverage, generous ESOP grants, catered gourmet food, state-of-the-art Apple hardware, wellness allowances.',
    '2026-03-17T15:30:00Z'::timestamptz,
    'https://cred.club/careers/job/staff-ui-designer',
    'published',
    true,
    'https://upload.wikimedia.org/wikipedia/en/thumb/7/7c/CRED_New_Logo.svg/320px-CRED_New_Logo.svg.png'
  ),
  -- 9. [UI Designer] Postman - UI Designer - API Workspace (Bengaluru)
  (
    '4c977894-7612-4666-a12c-837c9b8c38dd'::uuid,
    'Postman',
    'UI Designer - API Workspace',
    'UI Designer',
    'Bengaluru, Karnataka',
    'Remote',
    'Full time',
    '3-6 years',
    1800000,
    2800000,
    '₹18,00,000 - ₹28,00,000 / yr',
    'INR',
    ARRAY['Figma', 'Web UI', 'Developer Tooling UI', 'Component Libraries', 'Accessibility']::text[],
    'Design rich UI components for Postman desktop and web clients, including query editors, response inspectors, collections trees, and mock server consoles. Collaborate with engineering to maintain design system consistency across Electron and Web platforms.',
    '3-6 years designing developer tools, SaaS applications, or data-dense web platforms. In-depth understanding of UI architecture, typography for code, high-density layouts, and scalable Figma component libraries.',
    'Postman is used by 30+ million developers globally. We are looking for an experienced UI Designer in Bengaluru (Remote friendly) to make complex API workflows visually clean, intuitive, and lightning fast.',
    '100% remote flexibility with Bengaluru office access, wellness stipend, home-office budget, global health insurance, stock options (RSUs).',
    '2026-03-13T16:00:00Z'::timestamptz,
    'https://boards.greenhouse.io/postman/jobs/ui-designer-workspace',
    'published',
    false,
    'https://assets.getpostman.com/common-share/postman-logo-stacked.svg'
  ),
  -- 10. [UI Designer] Infosys - UI Designer - Digital Experience (Mysuru)
  (
    '87b0b818-7c37-41c7-9536-f5fb99805d80'::uuid,
    'Infosys',
    'UI Designer - Digital Experience',
    'UI Designer',
    'Mysuru, Karnataka',
    'Hybrid',
    'Full time',
    '3-6 years',
    800000,
    1400000,
    '₹8,00,000 - ₹14,00,000 / yr',
    'INR',
    ARRAY['Figma', 'Adobe XD', 'Responsive Web UI', 'HTML/CSS Awareness', 'Wireframing']::text[],
    'Translate enterprise business requirements into clean, user-friendly UI mockups and interactive prototypes for international clients. Conduct visual quality reviews with development squads during implementation phases.',
    '3+ years of experience in UI design for web and mobile applications. Proficient in Figma and Adobe XD. Strong grasp of responsive grids, icon design, and handoff workflows with front-end engineers.',
    'Infosys Center of Excellence in Mysuru is hiring a UI Designer. You will be part of a vibrant design studio delivering modern digital transformations for global retail, banking, and telecom clients.',
    'World-class campus amenities, comprehensive health benefits, retirement plans, structured learning at Mysuru GEC, on-campus sports facilities.',
    '2026-03-09T10:00:00Z'::timestamptz,
    'https://careers.infosys.com/job/ui-designer-mysuru',
    'published',
    false,
    'https://upload.wikimedia.org/wikipedia/commons/9/95/Infosys_logo.svg'
  ),
  -- 11. [UX Designer] Flipkart - Staff UX Designer - Customer Journey (Bengaluru)
  (
    'f569aa55-4aa4-488c-840b-8962f282294e'::uuid,
    'Flipkart',
    'Staff UX Designer - Customer Journey',
    'UX Designer',
    'Bengaluru, Karnataka',
    'Hybrid',
    'Full time',
    '6-10 years',
    2800000,
    4500000,
    '₹28,00,000 - ₹45,00,000 / yr',
    'INR',
    ARRAY['User Research', 'Information Architecture', 'User Journey Mapping', 'Figma', 'Usability Testing']::text[],
    'Architect end-to-end shopping journeys across search, product pages, and checkout for high-intent e-commerce categories. Conduct contextual customer interviews, run usability lab testing, synthesize behavioural telemetry, and translate insights into architectural improvements.',
    '6-10 years of dedicated UX design and user research experience in high-scale consumer applications. Mastery of information architecture, usability principles, card sorting, and user testing methodologies.',
    'Flipkart is seeking a Staff UX Designer in Bengaluru to lead user experience strategy for flagship consumer surfaces. You will partner with product executives to eliminate cognitive friction for millions of shoppers.',
    'Competitive base + attractive performance bonus + ESOPs, premium health insurance, wellness subsidies, relocation assistance to Bengaluru.',
    '2026-03-14T11:00:00Z'::timestamptz,
    'https://www.flipkartcareers.com/job/staff-ux-designer-customer-journey',
    'published',
    true,
    'https://upload.wikimedia.org/wikipedia/en/thumb/7/7a/Flipkart_logo.svg/320px-Flipkart_logo.svg.png'
  ),
  -- 12. [UX Designer] Swiggy - Senior UX Designer - Checkout & Delivery (Bengaluru)
  (
    'b57f1a24-89d5-4099-81c0-9dc0b66ef459'::uuid,
    'Swiggy',
    'Senior UX Designer - Checkout & Delivery',
    'UX Designer',
    'Bengaluru, Karnataka',
    'Hybrid',
    'Full time',
    '4-7 years',
    1800000,
    3000000,
    '₹18,00,000 - ₹30,00,000 / yr',
    'INR',
    ARRAY['Interaction Design', 'Heuristic Evaluation', 'Figma', 'Rapid Prototyping', 'User Flows']::text[],
    'Design streamlined cart, checkout, payment, and real-time order tracking experiences. Tackle multi-vendor ordering friction, address precision routing, and post-order support interactions with deep empathy for both consumers and delivery executives.',
    '4-7 years of interaction design and UX experience in hyper-growth consumer tech. Demonstrated ability to formulate hypotheses, run unmoderated user tests, and measure impact using retention and conversion metrics.',
    'Join Swiggy central UX team in Bengaluru. You will tackle real-world physical and digital constraints to make food delivery, grocery, and dining reservations feel seamless and stress-free.',
    'Hybrid working policy, comprehensive parental and family medical insurance, Swiggy food perks, paternity/maternity benefits, learning stipend.',
    '2026-03-12T14:30:00Z'::timestamptz,
    'https://swiggy.freshteam.com/jobs/senior-ux-designer-checkout',
    'published',
    false,
    'https://upload.wikimedia.org/wikipedia/en/thumb/1/12/Swiggy_logo.svg/320px-Swiggy_logo.svg.png'
  ),
  -- 13. [UX Designer] Zerodha - UX Designer - Kite Trading Platform (Bengaluru)
  (
    '3a03a82f-d731-443d-96bc-67359800a3e3'::uuid,
    'Zerodha',
    'UX Designer - Kite Trading Platform',
    'UX Designer',
    'Bengaluru, Karnataka',
    'Onsite',
    'Full time',
    '3-6 years',
    1500000,
    2500000,
    '₹15,00,000 - ₹25,00,000 / yr',
    'INR',
    ARRAY['Financial UX', 'Minimalist Design', 'Information Architecture', 'Figma', 'Qualitative Research']::text[],
    'Simplify complex financial market workflows including options chains, order execution types, portfolio analytics, and tax reports. Emphasize lightning-fast information retrieval, decluttered screens, and zero-distraction trading environments.',
    '3-6 years UX experience. Keen interest or background in Indian capital markets, trading, or personal finance. Strong commitment to minimalist, content-first user experience and ethical design patterns (no dark patterns).',
    'Zerodha Kite is India leading trading platform handling millions of trades daily. We are looking for a UX Designer at our JP Nagar, Bengaluru headquarters to help us build calm, fast, and transparent financial software.',
    'Competitive fixed compensation with zero arbitrary bonus structures, comprehensive health insurance, annual profit sharing, healthy office meals.',
    '2026-03-16T10:15:00Z'::timestamptz,
    'https://zerodha.com/careers/job/ux-designer-kite',
    'published',
    true,
    'https://zerodha.com/static/images/logo.svg'
  ),
  -- 14. [UX Designer] Ola - Lead UX Designer - Rider Platform (Bengaluru)
  (
    'a3bf9723-d841-4fca-b057-7cb109b3533e'::uuid,
    'Ola',
    'Lead UX Designer - Rider Platform',
    'UX Designer',
    'Bengaluru, Karnataka',
    'Onsite',
    'Full time',
    '5-8 years',
    2000000,
    3500000,
    '₹20,00,000 - ₹35,00,000 / yr',
    'INR',
    ARRAY['Service Design', 'Mobile UX', 'User Research', 'Usability Audits', 'Stakeholder Alignment']::text[],
    'Lead user experience design for Ola consumer mobility app across ride hailing, EV charging, and vehicle subscription journeys. Map multi-stakeholder service blueprints and drive usability audits across emerging tier-2 Indian geographies.',
    '5+ years UX design experience, preferably in mobility, logistics, or on-demand consumer applications. Strong expertise in service design, qualitative user interviews, and rapid interactive prototyping in Figma.',
    'Ola is looking for a Lead UX Designer in Bengaluru to reimagine urban mobility for millions of daily commuters. You will bridge digital interfaces with physical vehicles to deliver intuitive transit experiences.',
    'Health insurance for self and family, subsidized transport, gym facilities, employee discounts on Ola Electric purchases, gratuity.',
    '2026-03-07T12:00:00Z'::timestamptz,
    'https://www.olacabs.com/careers/job/lead-ux-designer-rider',
    'published',
    false,
    'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d9/Ola_Cabs_logo.svg/320px-Ola_Cabs_logo.svg.png'
  ),
  -- 15. [UX Designer] LTIMindtree - UX Designer - Enterprise Platforms (Mysuru)
  (
    '5924dc65-81cf-4af8-a909-10eb1b07dbb9'::uuid,
    'LTIMindtree',
    'UX Designer - Enterprise Platforms',
    'UX Designer',
    'Mysuru, Karnataka',
    'Hybrid',
    'Full time',
    '3-5 years',
    850000,
    1450000,
    '₹8,50,000 - ₹14,50,000 / yr',
    'INR',
    ARRAY['UX Research', 'Figma', 'Persona Creation', 'Task Analysis', 'Wireframing']::text[],
    'Conduct user interviews, cognitive walkthroughs, and workflow task analyses for enterprise SaaS products. Build wireframes and user journeys that reduce operational training time and simplify complex enterprise data entry tasks.',
    '3-5 years experience as a UX designer working on complex data systems or B2B platforms. Proficient in creating low and high fidelity wireframes in Figma. Strong communication skills with international stakeholders.',
    'LTIMindtree Mysuru center is hiring a UX Designer for its digital engineering practice. Work with global industrial and healthcare clients to modernize legacy enterprise workflows into delightful digital experiences.',
    'Health insurance, annual performance incentives, hybrid work schedule, technical certification sponsorship, sports and recreation access.',
    '2026-03-10T13:45:00Z'::timestamptz,
    'https://www.ltimindtree.com/careers/job/ux-designer-mysuru',
    'published',
    false,
    'https://upload.wikimedia.org/wikipedia/commons/thumb/5/53/LTIMindtree_Logo.svg/320px-LTIMindtree_Logo.svg.png'
  ),
  -- 16. [Product Designer] Razorpay - Senior Product Designer - Banking Suite (Bengaluru)
  (
    '7ad5299e-facc-4337-b106-461f2750161c'::uuid,
    'Razorpay',
    'Senior Product Designer - Banking Suite',
    'Product Designer',
    'Bengaluru, Karnataka',
    'Hybrid',
    'Full time',
    '4-8 years',
    2200000,
    3600000,
    '₹22,00,000 - ₹36,00,000 / yr',
    'INR',
    ARRAY['Product Strategy', 'Figma', 'User Research', 'Design Systems', 'Data Analysis']::text[],
    'Own end-to-end design for RazorpayX (Neo-banking & Corporate Cards for startups). Collaborate closely with product managers and engineers to discover customer pain points, define product roadmaps, and ship polished features.',
    '4-8 years of experience as a full-stack Product Designer across discovery, UX, UI, and post-launch validation. Strong analytical mindset with familiarity with product metrics (activation, drop-offs, retention).',
    'RazorpayX is revolutionizing business finance for Indian entrepreneurs. We are looking for a Senior Product Designer in Koramangala, Bengaluru to own the core financial command center for high-growth startups.',
    'Comprehensive health coverage, generous stock options, home office reimbursement, quarterly wellness days, continuous learning allowances.',
    '2026-03-13T10:00:00Z'::timestamptz,
    'https://razorpay.com/jobs/senior-product-designer-banking',
    'published',
    true,
    'https://upload.wikimedia.org/wikipedia/commons/8/89/Razorpay_logo.svg'
  ),
  -- 17. [Product Designer] Postman - Staff Product Designer - Cloud Platforms (Bengaluru)
  (
    '4c977894-7612-4666-a12c-837c9b8c38dd'::uuid,
    'Postman',
    'Staff Product Designer - Cloud Platforms',
    'Product Designer',
    'Bengaluru, Karnataka',
    'Remote',
    'Full time',
    '6-10 years',
    3000000,
    5000000,
    '₹30,00,000 - ₹50,00,000 / yr',
    'INR',
    ARRAY['Developer Experience', 'Product Thinking', 'Figma', 'Complex Systems Design', 'SaaS']::text[],
    'Lead product design strategy for Postman API Governance, Cloud Hub, and enterprise collaboration features. Partner with staff engineers and VP of Design to define multi-year platform architecture and seamless developer workflows.',
    '6+ years in product design with significant experience in developer tooling, cloud platforms, or complex enterprise software. Outstanding systems thinking, clear writing skills, and ability to navigate ambiguity.',
    'Postman is seeking a Staff Product Designer in Bengaluru to shape the future of API collaboration for global technology enterprises. Lead high-impact product initiatives that directly affect tens of millions of software engineers.',
    'Competitive salary + US equity (RSUs), remote-first work culture, home office setup stipend, comprehensive family medical and dental insurance.',
    '2026-03-15T14:00:00Z'::timestamptz,
    'https://boards.greenhouse.io/postman/jobs/staff-product-designer',
    'published',
    true,
    'https://assets.getpostman.com/common-share/postman-logo-stacked.svg'
  ),
  -- 18. [Product Designer] CRED - Product Designer - Financial Services (Bengaluru)
  (
    '7ee4aa16-22ec-4334-b274-e529864e53c8'::uuid,
    'CRED',
    'Product Designer - Financial Services',
    'Product Designer',
    'Bengaluru, Karnataka',
    'Onsite',
    'Full time',
    '3-6 years',
    2000000,
    3400000,
    '₹20,00,000 - ₹34,00,000 / yr',
    'INR',
    ARRAY['End-to-End Product Design', 'Visual Polish', 'Figma', 'Motion Guidelines', 'Product Metrics']::text[],
    'Design and ship end-to-end user experiences for CRED Cash (personal lines of credit), Mint (P2P lending), and wealth products. Drive discovery research, prototype bold concepts, and uphold the highest visual and interaction standards.',
    '3-6 years experience in product design at a top-tier tech company. Passion for elegant typography, motion, and interaction design. Proven ability to translate complex regulatory requirements into effortless user journeys.',
    'CRED is looking for an ambitious Product Designer in Bengaluru who is passionate about reinventing consumer finance. Build rewarding, transparent, and aesthetically captivating financial products for India top creditholders.',
    'Competitive base + ESOPs, comprehensive medical policy with mental health coverage, free gourmet meals, pet-friendly office, latest MacBook Pro.',
    '2026-03-12T16:20:00Z'::timestamptz,
    'https://cred.club/careers/job/product-designer-financial-services',
    'published',
    false,
    'https://upload.wikimedia.org/wikipedia/en/thumb/7/7c/CRED_New_Logo.svg/320px-CRED_New_Logo.svg.png'
  ),
  -- 19. [Product Designer] PhonePe - Lead Product Designer - Payments & UPI (Bengaluru)
  (
    'a6faf52b-f50a-4f98-9e03-62ec785d6e38'::uuid,
    'PhonePe',
    'Lead Product Designer - Payments & UPI',
    'Product Designer',
    'Bengaluru, Karnataka',
    'Onsite',
    'Full time',
    '5-8 years',
    2400000,
    3800000,
    '₹24,00,000 - ₹38,00,000 / yr',
    'INR',
    ARRAY['High-scale Products', 'Interaction Architecture', 'Figma', 'Product Discovery', 'Design Strategy']::text[],
    'Direct product design for core UPI transactions, recurring mandates, and wallet top-ups. Drive high-reliability interaction models that operate seamlessly even in low-bandwidth network environments across diverse linguistic demographics.',
    '5+ years experience designing consumer products with tens of millions of monthly active users. Strong command of interaction architecture, vernacular UI nuances, and quantitative design validation.',
    'PhonePe handles over 50% of all UPI transactions in India. As Lead Product Designer in Bengaluru, you will have the rare opportunity to shape the everyday financial habits of over 500 million registered users.',
    'Top-tier salary package, annual equity rewards, parental insurance, transportation services, health and wellness stipends.',
    '2026-03-09T11:30:00Z'::timestamptz,
    'https://www.phonepe.com/careers/job/lead-product-designer',
    'published',
    false,
    'https://upload.wikimedia.org/wikipedia/commons/7/71/PhonePe_Logo.svg'
  ),
  -- 20. [Product Designer] Cognizant India - Product Designer - Digital Products (Mangalore)
  (
    'c2567649-fe59-4405-8eec-ed6996a37990'::uuid,
    'Cognizant India',
    'Product Designer - Digital Products',
    'Product Designer',
    'Mangalore, Karnataka',
    'Hybrid',
    'Full time',
    '3-6 years',
    900000,
    1500000,
    '₹9,00,000 - ₹15,00,000 / yr',
    'INR',
    ARRAY['Product Lifecycle', 'Figma', 'Design Sprints', 'Client Collaboration', 'UI/UX']::text[],
    'Collaborate with international client product owners to conceptualize, wireframe, and test innovative digital web and mobile applications. Facilitate design sprints, define user stories, and deliver production-ready design specs.',
    '3-6 years of experience in product design or UI/UX consulting. Deep familiarity with Figma, modern design systems, and agile delivery frameworks. Strong presentation and stakeholder management abilities.',
    'Cognizant is hiring a Product Designer at our Mangalore delivery center. Work with leading global brands to bring customer-centric digital products to market across healthcare, retail, and financial domains.',
    'Hybrid work environment, comprehensive group health insurance, Provident Fund, higher education programs, annual performance increments.',
    '2026-03-06T15:00:00Z'::timestamptz,
    'https://careers.cognizant.com/job/product-designer-mangalore',
    'published',
    false,
    'https://upload.wikimedia.org/wikipedia/commons/thumb/9/95/Cognizant_logo_2022.svg/320px-Cognizant_logo_2022.svg.png'
  ),
  -- 21. [Motion Designer] CRED - Senior Motion Designer - Product Micro-animations (Bengaluru)
  (
    '7ee4aa16-22ec-4334-b274-e529864e53c8'::uuid,
    'CRED',
    'Senior Motion Designer - Product Micro-animations',
    'Motion Designer',
    'Bengaluru, Karnataka',
    'Onsite',
    'Full time',
    '4-7 years',
    2000000,
    3500000,
    '₹20,00,000 - ₹35,00,000 / yr',
    'INR',
    ARRAY['After Effects', 'Lottie', 'Cinema 4D', '3D Motion', 'Interactive Animation']::text[],
    'Design fluid micro-animations, payment success haptic loops, rewards unlocking rituals, and interactive 3D assets that live inside the CRED app. Partner with iOS and Android engineers to implement buttery-smooth 60fps animations.',
    '4+ years of motion graphics and in-app micro-interaction design experience. Mastery of Adobe After Effects, Cinema 4D/Blender, and Lottie export pipelines. Keen sensitivity to physics, momentum, easing curves, and spatial rhythm.',
    'CRED is looking for an extraordinary Senior Motion Designer in Indiranagar, Bengaluru. You will define the dynamic kinetic language that makes using CRED an exhilarating, sensory experience.',
    'Premium compensation + equity, holistic health cover, curated dining at the office, high-end Apple hardware and 3D rendering workstations.',
    '2026-03-14T17:00:00Z'::timestamptz,
    'https://cred.club/careers/job/senior-motion-designer',
    'published',
    true,
    'https://upload.wikimedia.org/wikipedia/en/thumb/7/7c/CRED_New_Logo.svg/320px-CRED_New_Logo.svg.png'
  ),
  -- 22. [Motion Designer] Swiggy - Motion Graphics Designer - Brand & Marketing (Bengaluru)
  (
    'b57f1a24-89d5-4099-81c0-9dc0b66ef459'::uuid,
    'Swiggy',
    'Motion Graphics Designer - Brand & Marketing',
    'Motion Designer',
    'Bengaluru, Karnataka',
    'Hybrid',
    'Full time',
    '3-6 years',
    1200000,
    1800000,
    '₹12,00,000 - ₹18,00,000 / yr',
    'INR',
    ARRAY['After Effects', 'Premiere Pro', '2D Animation', 'Motion Storytelling', 'Sound Design']::text[],
    'Create animated social media stories, YouTube bumper ads, digital billboard animations, and promotional motion content for Swiggy food festivals and Instamart trends. Work with copywriters and illustrators to storyboard and animate high-engagement videos.',
    '3-6 years in 2D animation, motion graphics, and video editing. Strong portfolio displaying character animation, kinetic typography, and sound synchronization using Adobe After Effects and Premiere Pro.',
    'Swiggy Creative Studio is seeking a Motion Graphics Designer in Bengaluru to bring playful, mouth-watering stories to life across all digital video channels. Turn witty scripts into viral motion campaigns.',
    'Health insurance, annual incentive plan, hybrid work setup, daily meal perks, wellness benefits.',
    '2026-03-11T13:00:00Z'::timestamptz,
    'https://swiggy.freshteam.com/jobs/motion-graphics-designer',
    'published',
    false,
    'https://upload.wikimedia.org/wikipedia/en/thumb/1/12/Swiggy_logo.svg/320px-Swiggy_logo.svg.png'
  ),
  -- 23. [Motion Designer] Flipkart - Motion Designer - Campaigns & Multimedia (Bengaluru)
  (
    'f569aa55-4aa4-488c-840b-8962f282294e'::uuid,
    'Flipkart',
    'Motion Designer - Campaigns & Multimedia',
    'Motion Designer',
    'Bengaluru, Karnataka',
    'Hybrid',
    'Full time',
    '3-5 years',
    1100000,
    1700000,
    '₹11,00,000 - ₹17,00,000 / yr',
    'INR',
    ARRAY['After Effects', 'Motion Typography', 'Promo Videos', 'Blender', 'Digital Storytelling']::text[],
    'Animate high-impact multimedia promos, festival teaser reels, brand partner showcase videos, and in-app video feeds for Flipkart flagship sales. Ensure assets are optimized for fast loading and crisp playback across mobile displays.',
    '3-5 years of motion graphics experience in an e-commerce, advertising, or broadcast agency setting. Expert knowledge of After Effects, video compression formats, and 3D modeling tools such as Blender.',
    'Join Flipkart Marketing Communications team in Bengaluru. We are looking for an innovative Motion Designer to produce dynamic video creatives seen by hundreds of millions of Indian shoppers.',
    'Medical insurance covering parents and spouse, annual performance bonus, internet and phone bills reimbursement, employee discounts.',
    '2026-03-13T12:00:00Z'::timestamptz,
    'https://www.flipkartcareers.com/job/motion-designer-campaigns',
    'published',
    false,
    'https://upload.wikimedia.org/wikipedia/en/thumb/7/7a/Flipkart_logo.svg/320px-Flipkart_logo.svg.png'
  ),
  -- 24. [Motion Designer] Ola - Lead Motion Designer - Vehicle & App Interface (Bengaluru)
  (
    'a3bf9723-d841-4fca-b057-7cb109b3533e'::uuid,
    'Ola',
    'Lead Motion Designer - Vehicle & App Interface',
    'Motion Designer',
    'Bengaluru, Karnataka',
    'Onsite',
    'Full time',
    '5-8 years',
    1800000,
    2800000,
    '₹18,00,000 - ₹28,00,000 / yr',
    'INR',
    ARRAY['HMI Animation', 'Lottie', 'After Effects', '3D Visualization', 'Micro-interactions']::text[],
    'Design and prototype animations for the Ola Electric scooter instrument clusters (MoveOS) and the Ola companion mobile apps. Create futuristic digital gauge clusters, charging animations, navigation transitions, and audio-visual drive-mode cues.',
    '5+ years experience designing motion for automotive HMI, gaming, or premium mobile applications. Deep expertise in After Effects, real-time animation constraints, and state-driven UI motion.',
    'Ola Electric is transforming personal mobility worldwide. As Lead Motion Designer at our Bengaluru campus, you will craft the futuristic animated interface that drivers interact with on every journey.',
    'Competitive package, health and life insurance, subsidised gym and sports access, employee vehicle purchase benefits.',
    '2026-03-08T14:30:00Z'::timestamptz,
    'https://www.olacabs.com/careers/job/lead-motion-designer',
    'published',
    true,
    'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d9/Ola_Cabs_logo.svg/320px-Ola_Cabs_logo.svg.png'
  ),
  -- 25. [Motion Designer] Cognizant India - Motion Graphics Designer - Digital Media (Mangalore)
  (
    'c2567649-fe59-4405-8eec-ed6996a37990'::uuid,
    'Cognizant India',
    'Motion Graphics Designer - Digital Media',
    'Motion Designer',
    'Mangalore, Karnataka',
    'Onsite',
    'Full time',
    '2-5 years',
    700000,
    1150000,
    '₹7,00,000 - ₹11,50,000 / yr',
    'INR',
    ARRAY['After Effects', 'Premiere Pro', 'Video Editing', 'Explainer Videos', 'Motion Graphics']::text[],
    'Produce animated explainer videos, customer case study animations, and digital training modules for enterprise clients. Assemble motion sequences, kinetic text, voiceover sync, and background scores into polished deliverables.',
    '2-5 years of motion graphics experience. Proficient in Adobe After Effects, Premiere Pro, and Illustrator. Good understanding of video codecs, audio editing, and visual pacing.',
    'Cognizant is seeking a Motion Graphics Designer for its creative delivery hub in Mangalore. Collaborate with global corporate clients to explain complex technology architectures through clear, captivating animated videos.',
    'Corporate insurance coverage, annual performance bonus, professional development courses, recreational campus amenities.',
    '2026-03-05T10:15:00Z'::timestamptz,
    'https://careers.cognizant.com/job/motion-designer-mangalore',
    'published',
    false,
    'https://upload.wikimedia.org/wikipedia/commons/thumb/9/95/Cognizant_logo_2022.svg/320px-Cognizant_logo_2022.svg.png'
  ),
  -- 26. [Brand Designer] Zerodha - Brand Identity Designer (Bengaluru)
  (
    '3a03a82f-d731-443d-96bc-67359800a3e3'::uuid,
    'Zerodha',
    'Brand Identity Designer',
    'Brand Designer',
    'Bengaluru, Karnataka',
    'Onsite',
    'Full time',
    '3-6 years',
    1400000,
    2200000,
    '₹14,00,000 - ₹22,00,000 / yr',
    'INR',
    ARRAY['Brand Identity', 'Typography', 'Visual Systems', 'Logo Design', 'Print & Digital']::text[],
    'Guard and cultivate the Zerodha brand identity across all touchpoints including Rainmatter, Varsity, Coin, and Zerodha publications. Design authentic brand assets, educational book layouts, conference branding, and merchandise with timeless aesthetic restraint.',
    '3-6 years experience in brand identity and typography design. Exceptional portfolio showcasing brand systems, custom typography, and print craft. Deep appreciation for authentic, non-corporate visual expression.',
    'Zerodha is looking for a thoughtful Brand Identity Designer at our Bengaluru office. We avoid hype and aggressive marketing; we need someone who can express our focus on education, ethics, and clarity through beautiful brand design.',
    'Predictable fixed compensation with no gimmicky targets, comprehensive medical insurance, delicious healthy meals prepared on-site, generous leave policies.',
    '2026-03-15T09:30:00Z'::timestamptz,
    'https://zerodha.com/careers/job/brand-identity-designer',
    'published',
    true,
    'https://zerodha.com/static/images/logo.svg'
  ),
  -- 27. [Brand Designer] Myntra - Senior Brand Designer - Lifestyle & Studio (Bengaluru)
  (
    '5101f225-e0d5-459d-928e-6bdc68fb8e23'::uuid,
    'Myntra',
    'Senior Brand Designer - Lifestyle & Studio',
    'Brand Designer',
    'Bengaluru, Karnataka',
    'Hybrid',
    'Full time',
    '4-7 years',
    1500000,
    2400000,
    '₹15,00,000 - ₹24,00,000 / yr',
    'INR',
    ARRAY['Brand Strategy', 'Art Direction', 'Editorial Design', 'Illustrator', 'Style Guides']::text[],
    'Develop comprehensive brand guidelines, visual guidelines, and seasonal campaign identities for Myntra in-house private labels (Roadster, HRX, Anouk, Mast & Harbour). Collaborate with merchandising and packaging designers to ensure cohesive brand worlds.',
    '4-7 years brand design experience in fashion, apparel, or premium lifestyle brands. Mastery of brand storytelling, packaging design, and visual brand language development.',
    'Myntra is hiring a Senior Brand Designer in Bengaluru to lead the visual identity for India most popular lifestyle and fashion labels. Help craft iconic brands that connect emotionally with young India.',
    'Subsidized health insurance, employee clothing discounts, flexible hybrid working model, wellness benefits, parental leave.',
    '2026-03-12T11:00:00Z'::timestamptz,
    'https://careers.myntra.com/jobs/senior-brand-designer',
    'published',
    false,
    'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d5/Myntra_logo.png/320px-Myntra_logo.png'
  ),
  -- 28. [Brand Designer] Razorpay - Brand Experience Designer - Marketing (Bengaluru)
  (
    '7ad5299e-facc-4337-b106-461f2750161c'::uuid,
    'Razorpay',
    'Brand Experience Designer - Marketing',
    'Brand Designer',
    'Bengaluru, Karnataka',
    'Hybrid',
    'Full time',
    '3-5 years',
    1300000,
    2000000,
    '₹13,00,000 - ₹20,00,000 / yr',
    'INR',
    ARRAY['Brand Architecture', 'Figma', 'Illustration Systems', 'Marketing Collateral', 'Iconography']::text[],
    'Design brand experiences for Razorpay flagship events (FTX), partner summits, customer case studies, and corporate marketing initiatives. Ensure brand consistency across offline spatial setups, physical swag, and digital landing pages.',
    '3-5 years of brand and experiential design experience. Strong background in corporate visual identity systems, illustration styles, and large-format environmental graphics.',
    'Join the Razorpay Design team in Bengaluru as a Brand Experience Designer. You will help reinforce Razorpay status as India most trusted, innovative fintech brand through cohesive, memorable design touchpoints.',
    'Medical insurance for family, ESOPs, annual learning grant, home-office upgrade budget, flexible hybrid hours.',
    '2026-03-10T16:00:00Z'::timestamptz,
    'https://razorpay.com/jobs/brand-experience-designer',
    'published',
    false,
    'https://upload.wikimedia.org/wikipedia/commons/8/89/Razorpay_logo.svg'
  ),
  -- 29. [Brand Designer] BigBasket - Brand Designer - Private Labels (Bengaluru)
  (
    '40393f4e-a82d-4606-8e07-b5ea63fd592d'::uuid,
    'BigBasket',
    'Brand Designer - Private Labels',
    'Brand Designer',
    'Bengaluru, Karnataka',
    'Onsite',
    'Full time',
    '3-6 years',
    1000000,
    1600000,
    '₹10,00,000 - ₹16,00,000 / yr',
    'INR',
    ARRAY['Packaging Design', 'Brand Guidelines', 'Adobe Creative Suite', 'FMCG Branding', 'Print Production']::text[],
    'Design packaging architectures, label systems, and brand guidelines for BigBasket private brands across organic produce, gourmet staples, and FMCG lines. Supervise prepress production and liaise with print vendors to guarantee fidelity.',
    '3-6 years experience in packaging and brand design for consumer goods/FMCG. Deep technical understanding of packaging materials, printing processes (flexo, gravure, offset), and regulatory packaging standards in India.',
    'BigBasket is looking for a Brand Designer in Bengaluru specializing in retail packaging and brand development. Shape the physical look and feel of products that land in millions of kitchen pantries every week.',
    'Dependent health insurance, grocery shopping discounts, PF, gratuity, yearly bonus plan.',
    '2026-03-14T10:00:00Z'::timestamptz,
    'https://careers.bigbasket.com/job/brand-designer-private-labels',
    'published',
    false,
    'https://upload.wikimedia.org/wikipedia/en/thumb/0/07/Bigbasket_Logo.svg/320px-Bigbasket_Logo.svg.png'
  ),
  -- 30. [Brand Designer] Infosys - Brand & Communications Designer (Mangalore)
  (
    '87b0b818-7c37-41c7-9536-f5fb99805d80'::uuid,
    'Infosys',
    'Brand & Communications Designer',
    'Brand Designer',
    'Mangalore, Karnataka',
    'Hybrid',
    'Full time',
    '3-6 years',
    800000,
    1300000,
    '₹8,00,000 - ₹13,00,000 / yr',
    'INR',
    ARRAY['Corporate Branding', 'Visual Identity', 'Presentations', 'InDesign', 'Brand Governance']::text[],
    'Oversee corporate visual governance, global marketing collateral, and digital brand consistency for Infosys business units. Review marketing materials from regional offices to ensure adherence to brand typography, color systems, and iconography.',
    '3-6 years experience in brand design and corporate communications. Expertise in Adobe InDesign, Illustrator, and Photoshop. Excellent eye for layout harmony, brand compliance, and corporate messaging.',
    'Infosys Mangalore DC is hiring a Brand & Communications Designer. Play a central role in protecting and evolving the brand image of one of India most renowned global enterprise brands.',
    'Health insurance, annual performance incentives, transport facility, professional training and certification courses.',
    '2026-03-09T14:30:00Z'::timestamptz,
    'https://careers.infosys.com/job/brand-designer-mangalore',
    'published',
    false,
    'https://upload.wikimedia.org/wikipedia/commons/9/95/Infosys_logo.svg'
  ),
  -- 31. [Visual Designer] CRED - Visual Designer - Surfaces & Editorial (Bengaluru)
  (
    '7ee4aa16-22ec-4334-b274-e529864e53c8'::uuid,
    'CRED',
    'Visual Designer - Surfaces & Editorial',
    'Visual Designer',
    'Bengaluru, Karnataka',
    'Onsite',
    'Full time',
    '3-6 years',
    1800000,
    3000000,
    '₹18,00,000 - ₹30,00,000 / yr',
    'INR',
    ARRAY['Visual Craft', '3D Rendering', 'Figma', 'Typography', 'Color Theory']::text[],
    'Design rich graphical surfaces, editorial cards, luxury brand partnership treatments, and promotional splash screens inside the CRED app. Experiment with 3D modeling, dynamic lighting, and modern visual art styles.',
    '3-6 years experience in visual design for mobile apps or premium digital agencies. Portfolio demonstrating world-class graphic sensitivity, color theory, 3D elements, and meticulous attention to detail.',
    'Join CRED elite design team in Bengaluru as a Visual Designer. We seek creators who treat every pixel as an opportunity for artistic expression and delight, producing high-impact visual surfaces.',
    'Industry-leading compensation, ESOPs, comprehensive healthcare, catered food, state-of-the-art work gear.',
    '2026-03-16T11:00:00Z'::timestamptz,
    'https://cred.club/careers/job/visual-designer-surfaces',
    'published',
    true,
    'https://upload.wikimedia.org/wikipedia/en/thumb/7/7c/CRED_New_Logo.svg/320px-CRED_New_Logo.svg.png'
  ),
  -- 32. [Visual Designer] PhonePe - Senior Visual Designer - Consumer App (Bengaluru)
  (
    'a6faf52b-f50a-4f98-9e03-62ec785d6e38'::uuid,
    'PhonePe',
    'Senior Visual Designer - Consumer App',
    'Visual Designer',
    'Bengaluru, Karnataka',
    'Onsite',
    'Full time',
    '4-7 years',
    1600000,
    2500000,
    '₹16,00,000 - ₹25,00,000 / yr',
    'INR',
    ARRAY['Visual Design', 'Design Systems', 'Figma', 'Illustrator', 'Iconography']::text[],
    'Craft visually stunning headers, illustrations, reward scratch-cards, and promotional widgets for the PhonePe consumer app. Collaborate with the design systems team to create and maintain a comprehensive iconography and graphic asset library.',
    '4-7 years of visual design experience in top consumer tech apps. Mastery of Figma, vector illustration, and iconography systems. Strong understanding of visual hierarchy across varied mobile screen densities.',
    'PhonePe is seeking a Senior Visual Designer in Bengaluru to bring visual delight to everyday financial transactions. Your work will be enjoyed by hundreds of millions of smartphone users across India.',
    'Full family medical coverage, annual bonus, complimentary meals, cab allowances, retirement benefits.',
    '2026-03-11T15:00:00Z'::timestamptz,
    'https://www.phonepe.com/careers/job/senior-visual-designer',
    'published',
    false,
    'https://upload.wikimedia.org/wikipedia/commons/7/71/PhonePe_Logo.svg'
  ),
  -- 33. [Visual Designer] Flipkart - Visual Designer - Category Merchandising (Bengaluru)
  (
    'f569aa55-4aa4-488c-840b-8962f282294e'::uuid,
    'Flipkart',
    'Visual Designer - Category Merchandising',
    'Visual Designer',
    'Bengaluru, Karnataka',
    'Hybrid',
    'Full time',
    '2-5 years',
    900000,
    1500000,
    '₹9,00,000 - ₹15,00,000 / yr',
    'INR',
    ARRAY['Visual Merchandising', 'Photoshop', 'Graphic Layout', 'Digital Ads', 'Figma']::text[],
    'Design category storefront banners, flash deal graphics, curated collection hubs, and promotional banners for Electronics and Fashion verticals on Flipkart. Optimize visual compositions for high click-through rates and brand prestige.',
    '2-5 years in visual design for e-commerce, retail, or ad agencies. Expert proficiency in Adobe Photoshop and Figma. Quick turnaround ability and solid understanding of customer buying psychology.',
    'Flipkart is hiring a Visual Designer in Bengaluru to create visually compelling merchandising assets. Help guide shoppers to top deals and discover products through clean, attractive visual presentations.',
    'Comprehensive health cover, annual performance incentives, hybrid work schedule, mobile reimbursement, employee shopping discounts.',
    '2026-03-13T09:15:00Z'::timestamptz,
    'https://www.flipkartcareers.com/job/visual-designer-merchandising',
    'published',
    false,
    'https://upload.wikimedia.org/wikipedia/en/thumb/7/7a/Flipkart_logo.svg/320px-Flipkart_logo.svg.png'
  ),
  -- 34. [Visual Designer] Postman - Visual Designer - Marketing & Web (Bengaluru)
  (
    '4c977894-7612-4666-a12c-837c9b8c38dd'::uuid,
    'Postman',
    'Visual Designer - Marketing & Web',
    'Visual Designer',
    'Bengaluru, Karnataka',
    'Remote',
    'Full time',
    '3-5 years',
    1500000,
    2300000,
    '₹15,00,000 - ₹23,00,000 / yr',
    'INR',
    ARRAY['Web Visuals', 'Illustration', 'Figma', 'Brand Cohesion', 'Digital Assets']::text[],
    'Design engaging visual assets for Postman marketing website, product announcement landing pages, developer conferences, and blog posts. Collaborate with content and web engineering squads to maintain vibrant, developer-friendly brand visuals.',
    '3-5 years of visual and web graphic design experience. Proficiency in Figma and vector illustration. Passion for developer culture and technical storytelling through visual art.',
    'Postman is seeking a remote Visual Designer based in Karnataka to amplify our developer brand. Create inspiring illustrations, diagrams, and web layouts that communicate the power of APIs to millions of engineers.',
    'Flexible work from anywhere, annual home-office stipend, global medical insurance, stock equity options, learning & education budgets.',
    '2026-03-12T15:45:00Z'::timestamptz,
    'https://boards.greenhouse.io/postman/jobs/visual-designer-marketing',
    'published',
    false,
    'https://assets.getpostman.com/common-share/postman-logo-stacked.svg'
  ),
  -- 35. [Visual Designer] Cognizant India - Visual Designer - Enterprise Applications (Mangalore)
  (
    'c2567649-fe59-4405-8eec-ed6996a37990'::uuid,
    'Cognizant India',
    'Visual Designer - Enterprise Applications',
    'Visual Designer',
    'Mangalore, Karnataka',
    'Hybrid',
    'Full time',
    '3-5 years',
    750000,
    1250000,
    '₹7,50,000 - ₹12,50,000 / yr',
    'INR',
    ARRAY['Visual Design', 'Figma', 'Style Guides', 'UI Components', 'Design Handoff']::text[],
    'Create visual style guides, component themes, color palettes, and polished UI screens for enterprise web and cloud applications. Partner with UX researchers and software developers to ensure high visual fidelity in shipped software.',
    '3-5 years experience in visual design for enterprise or consumer software. Proficient in Figma and Adobe Suite. Clear understanding of design tokens, accessibility, and design handoff.',
    'Join Cognizant growing digital design practice in Mangalore. We are looking for a skilled Visual Designer to craft crisp, modern, and accessible visual interfaces for international enterprise clients.',
    'Medical insurance covering immediate family, annual bonus, flexible working hours, ongoing upskilling and training programs.',
    '2026-03-07T11:00:00Z'::timestamptz,
    'https://careers.cognizant.com/job/visual-designer-mangalore',
    'published',
    false,
    'https://upload.wikimedia.org/wikipedia/commons/thumb/9/95/Cognizant_logo_2022.svg/320px-Cognizant_logo_2022.svg.png'
  ),
  -- 36. [Digital Marketing] Swiggy - Performance Marketing Manager - Growth (Bengaluru)
  (
    'b57f1a24-89d5-4099-81c0-9dc0b66ef459'::uuid,
    'Swiggy',
    'Performance Marketing Manager - Growth',
    'Digital Marketing',
    'Bengaluru, Karnataka',
    'Hybrid',
    'Full time',
    '4-7 years',
    1800000,
    2800000,
    '₹18,00,000 - ₹28,00,000 / yr',
    'INR',
    ARRAY['Google Ads', 'Meta Ads', 'App Attribution', 'CAC Optimization', 'Analytics']::text[],
    'Manage multi-crore monthly advertising budgets across Google UAC, Meta Ads Manager, Apple Search Ads, and programmatic DSPs. Optimize customer acquisition costs (CAC) and customer lifetime value (LTV) for Swiggy Food and Instamart.',
    '4-7 years in performance marketing or paid acquisition for hyper-scale mobile apps. In-depth understanding of mobile measurement partners (MMPs like AppsFlyer/Branch), cohort analysis, and incrementality testing.',
    'Swiggy is seeking an analytical, data-driven Performance Marketing Manager in Bengaluru to spearhead paid user acquisition and retargeting campaigns at massive scale across Indian metros and tier-2/3 cities.',
    'Comprehensive health coverage, annual performance bonus, hybrid work policy, food allowances, mental health and wellness support.',
    '2026-03-14T10:30:00Z'::timestamptz,
    'https://swiggy.freshteam.com/jobs/performance-marketing-manager',
    'published',
    true,
    'https://upload.wikimedia.org/wikipedia/en/thumb/1/12/Swiggy_logo.svg/320px-Swiggy_logo.svg.png'
  ),
  -- 37. [Digital Marketing] Razorpay - Digital Marketing Lead - B2B SaaS (Bengaluru)
  (
    '7ad5299e-facc-4337-b106-461f2750161c'::uuid,
    'Razorpay',
    'Digital Marketing Lead - B2B SaaS',
    'Digital Marketing',
    'Bengaluru, Karnataka',
    'Hybrid',
    'Full time',
    '5-8 years',
    2000000,
    3200000,
    '₹20,00,000 - ₹32,00,000 / yr',
    'INR',
    ARRAY['B2B Marketing', 'SEO', 'Demand Generation', 'HubSpot', 'LinkedIn Ads']::text[],
    'Lead inbound demand generation, organic search (SEO), and paid enterprise acquisition for Razorpay banking and payment gateway solutions. Build multi-channel funnel campaigns targeting founders, CTOs, and CFOs.',
    '5-8 years experience in B2B digital marketing, SaaS demand generation, or growth marketing. Hands-on expertise in LinkedIn Campaign Manager, Google Search Ads, HubSpot CRM, and Google Analytics 4.',
    'Razorpay is looking for a Digital Marketing Lead in Bengaluru to accelerate merchant acquisition for our suite of fintech products. Drive predictable pipeline growth through sophisticated inbound marketing and performance funnels.',
    'Complete medical insurance, ESOP allocation, annual learning stipend, home office allowance, flexible working arrangements.',
    '2026-03-12T12:00:00Z'::timestamptz,
    'https://razorpay.com/jobs/digital-marketing-lead',
    'published',
    true,
    'https://upload.wikimedia.org/wikipedia/commons/8/89/Razorpay_logo.svg'
  ),
  -- 38. [Digital Marketing] Myntra - SEO & Content Marketing Specialist (Bengaluru)
  (
    '5101f225-e0d5-459d-928e-6bdc68fb8e23'::uuid,
    'Myntra',
    'SEO & Content Marketing Specialist',
    'Digital Marketing',
    'Bengaluru, Karnataka',
    'Hybrid',
    'Full time',
    '3-5 years',
    1000000,
    1600000,
    '₹10,00,000 - ₹16,00,000 / yr',
    'INR',
    ARRAY['Technical SEO', 'Keyword Research', 'Google Analytics', 'Ahrefs', 'Content Strategy']::text[],
    'Drive organic search visibility and revenue for millions of product category and brand pages on Myntra. Conduct deep keyword research, technical SEO audits (crawl budget, core web vitals, structured data), and content gap analyses.',
    '3-5 years experience driving enterprise SEO for large e-commerce or publishing websites. Proficient in Ahrefs, SEMrush, Screaming Frog, and Google Search Console. Solid understanding of technical site architecture.',
    'Myntra is hiring an SEO & Content Marketing Specialist in Bengaluru. Scale organic acquisition channels to reach millions of fashion shoppers seeking top apparel, footwear, and beauty brands.',
    'Medical insurance including parents, employee discounts, hybrid working schedule, wellness allowances.',
    '2026-03-10T14:00:00Z'::timestamptz,
    'https://careers.myntra.com/jobs/seo-content-specialist',
    'published',
    false,
    'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d5/Myntra_logo.png/320px-Myntra_logo.png'
  ),
  -- 39. [Digital Marketing] Zerodha - Digital Marketing & Community Associate (Bengaluru)
  (
    '3a03a82f-d731-443d-96bc-67359800a3e3'::uuid,
    'Zerodha',
    'Digital Marketing & Community Associate',
    'Digital Marketing',
    'Bengaluru, Karnataka',
    'Onsite',
    'Full time',
    '2-4 years',
    800000,
    1300000,
    '₹8,00,000 - ₹13,00,000 / yr',
    'INR',
    ARRAY['Community Engagement', 'Social Media Marketing', 'Newsletter Strategy', 'Copywriting', 'Analytics']::text[],
    'Manage official Zerodha social media communications, investor education newsletters, and TradingQ&A community moderation. Draft clear, engaging, and jargon-free updates explaining capital markets, product launches, and regulatory circulars.',
    '2-4 years experience in digital communication, content marketing, or financial journalism. Exceptional English writing skills. Genuine interest in personal finance, financial literacy, and Indian stock markets.',
    'Join Zerodha organic communications team in JP Nagar, Bengaluru. We do not do aggressive push marketing; we educate investors. You will help build and nurture the most informed trading community in India.',
    'Competitive fixed compensation with zero commission bias, health insurance, free nutritious meals at the office, retirement benefits.',
    '2026-03-15T11:45:00Z'::timestamptz,
    'https://zerodha.com/careers/job/marketing-associate',
    'published',
    false,
    'https://zerodha.com/static/images/logo.svg'
  ),
  -- 40. [Digital Marketing] Wipro - Digital Marketing Specialist - Global Campaigns (Mysuru)
  (
    '32a33ef9-eac4-404e-b4b3-83817f71081f'::uuid,
    'Wipro',
    'Digital Marketing Specialist - Global Campaigns',
    'Digital Marketing',
    'Mysuru, Karnataka',
    'Hybrid',
    'Full time',
    '3-6 years',
    750000,
    1300000,
    '₹7,50,000 - ₹13,00,000 / yr',
    'INR',
    ARRAY['Email Marketing', 'Marketo', 'Google Analytics', 'Campaign Management', 'Social Media']::text[],
    'Execute global digital marketing campaigns, webinar promotion funnels, and email nurture tracks for Wipro cloud and cybersecurity practices. Monitor lead conversion metrics in CRM and optimize engagement across international geos.',
    '3-6 years experience in B2B digital marketing or IT services marketing. Experience with marketing automation platforms such as Marketo or HubSpot. Solid analytical mindset with proficiency in reporting dashboards.',
    'Wipro is hiring a Digital Marketing Specialist at its campus in Hebbal, Mysuru. Help plan and deliver omnichannel global campaigns that showcase Wipro innovative IT consulting and digital engineering services.',
    'Corporate health coverage, annual performance bonus, transport facility, higher education assistance, sports complex access.',
    '2026-03-08T16:00:00Z'::timestamptz,
    'https://careers.wipro.com/job/digital-marketing-specialist-mysuru',
    'published',
    false,
    'https://upload.wikimedia.org/wikipedia/commons/a/a0/Wipro_Primary_Logo_Color_RGB.svg'
  ),
  -- 41. [Frontend Developer] Flipkart - SDE II - Frontend Engineering (Bengaluru)
  (
    'f569aa55-4aa4-488c-840b-8962f282294e'::uuid,
    'Flipkart',
    'SDE II - Frontend Engineering',
    'Frontend Developer',
    'Bengaluru, Karnataka',
    'Hybrid',
    'Full time',
    '3-6 years',
    2200000,
    3800000,
    '₹22,00,000 - ₹38,00,000 / yr',
    'INR',
    ARRAY['React', 'TypeScript', 'Next.js', 'Web Performance', 'Redux']::text[],
    'Build lightning-fast, high-availability web applications for Flipkart customer-facing platforms. Optimize Core Web Vitals (LCP, INP, CLS), architect modular component libraries, and handle complex state for high-concurrency festival traffic.',
    '3-6 years of professional frontend engineering experience. Deep mastery of JavaScript (ES6+), TypeScript, React, and browser rendering internals. Proven experience optimizing web performance for low-end mobile devices.',
    'Flipkart is looking for a talented SDE II Frontend Engineer in Bengaluru. You will engineer ultra-resilient web architectures that power millions of transactions per hour during The Big Billion Days.',
    'Competitive base + ESOPs + performance bonus, medical insurance for entire family, relocation allowance, hybrid work flexibility.',
    '2026-03-14T09:00:00Z'::timestamptz,
    'https://www.flipkartcareers.com/job/sde-2-frontend',
    'published',
    true,
    'https://upload.wikimedia.org/wikipedia/en/thumb/7/7a/Flipkart_logo.svg/320px-Flipkart_logo.svg.png'
  ),
  -- 42. [Frontend Developer] Postman - Senior Frontend Engineer - Developer Workspace (Bengaluru)
  (
    '4c977894-7612-4666-a12c-837c9b8c38dd'::uuid,
    'Postman',
    'Senior Frontend Engineer - Developer Workspace',
    'Frontend Developer',
    'Bengaluru, Karnataka',
    'Remote',
    'Full time',
    '4-8 years',
    2800000,
    4600000,
    '₹28,00,000 - ₹46,00,000 / yr',
    'INR',
    ARRAY['JavaScript', 'React', 'Electron', 'Node.js', 'WebSockets']::text[],
    'Architect and enhance the core Postman API client interface across Desktop (Electron) and Web applications. Implement high-performance data grids, virtualized lists, WebSocket streaming clients, and extensible plugin architectures.',
    '4-8 years of experience building complex, desktop-grade web applications. Mastery of React, JavaScript memory management, Web Workers, and state synchronization. Familiarity with developer tooling and API protocols.',
    'Postman is seeking a Senior Frontend Engineer in Bengaluru (Remote friendly). Help build the workbench that 30+ million developers use daily to test, document, and collaborate on APIs across the globe.',
    'Work from anywhere within India, competitive US equity (RSUs), comprehensive health insurance, ergonomic home office allowance, continuous learning budget.',
    '2026-03-15T15:00:00Z'::timestamptz,
    'https://boards.greenhouse.io/postman/jobs/senior-frontend-engineer',
    'published',
    true,
    'https://assets.getpostman.com/common-share/postman-logo-stacked.svg'
  ),
  -- 43. [Frontend Developer] PhonePe - Software Engineer - Web Frontend (Bengaluru)
  (
    'a6faf52b-f50a-4f98-9e03-62ec785d6e38'::uuid,
    'PhonePe',
    'Software Engineer - Web Frontend',
    'Frontend Developer',
    'Bengaluru, Karnataka',
    'Onsite',
    'Full time',
    '2-5 years',
    1600000,
    2800000,
    '₹16,00,000 - ₹28,00,000 / yr',
    'INR',
    ARRAY['React', 'TypeScript', 'CSS3', 'REST APIs', 'Webpack']::text[],
    'Develop high-performance merchant portals, analytics dashboards, and web-view micro-frontends embedded within the PhonePe mobile apps. Ensure sub-second page loads, rigorous cross-browser compatibility, and bulletproof security.',
    '2-5 years hands-on frontend engineering experience. Proficient in React, TypeScript, responsive CSS, and state management (Zustand/Redux). Strong debugging skills using browser developer tools and automated tests.',
    'Join the PhonePe engineering squad at our Bengaluru headquarters. Build high-concurrency web applications that empower millions of business merchants to track revenue and reconcile settlements seamlessly.',
    'Top-tier salary package, annual incentive bonuses, comprehensive health coverage with parent inclusion, complimentary gourmet meals, cab transport.',
    '2026-03-11T11:00:00Z'::timestamptz,
    'https://www.phonepe.com/careers/job/software-engineer-frontend',
    'published',
    false,
    'https://upload.wikimedia.org/wikipedia/commons/7/71/PhonePe_Logo.svg'
  ),
  -- 44. [Frontend Developer] Ola - Lead Frontend Architect - Fleet Management (Bengaluru)
  (
    'a3bf9723-d841-4fca-b057-7cb109b3533e'::uuid,
    'Ola',
    'Lead Frontend Architect - Fleet Management',
    'Frontend Developer',
    'Bengaluru, Karnataka',
    'Onsite',
    'Full time',
    '6-10 years',
    3000000,
    5000000,
    '₹30,00,000 - ₹50,00,000 / yr',
    'INR',
    ARRAY['Micro-frontends', 'React', 'TypeScript', 'State Management', 'Core Web Vitals']::text[],
    'Lead technical design and frontend architecture for the Ola Fleet & Mobility Command Center. Guide squads of frontend developers, establish CI/CD quality gates, implement micro-frontends, and drive real-time telemetry visualizations on interactive geospatial maps.',
    '6-10 years frontend engineering with experience leading complex web architecture. Deep expertise in React, TypeScript, Mapbox/WebGL, WebSockets, and scalable frontend state management.',
    'Ola is looking for a Lead Frontend Architect in Bengaluru to build mission-critical mission-control dashboards for global electric vehicle fleets, gig charging networks, and driver partner operations.',
    'Industry-leading compensation + stock options, premium healthcare, subsidized transport, employee EV benefits, gratuity.',
    '2026-03-09T13:00:00Z'::timestamptz,
    'https://www.olacabs.com/careers/job/lead-frontend-architect',
    'published',
    false,
    'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d9/Ola_Cabs_logo.svg/320px-Ola_Cabs_logo.svg.png'
  ),
  -- 45. [Frontend Developer] Infosys - Senior Systems Engineer - Frontend (React) (Mysuru)
  (
    '87b0b818-7c37-41c7-9536-f5fb99805d80'::uuid,
    'Infosys',
    'Senior Systems Engineer - Frontend (React)',
    'Frontend Developer',
    'Mysuru, Karnataka',
    'Hybrid',
    'Full time',
    '3-5 years',
    800000,
    1400000,
    '₹8,00,000 - ₹14,00,000 / yr',
    'INR',
    ARRAY['React', 'JavaScript', 'HTML5', 'CSS3', 'Git']::text[],
    'Develop and maintain responsive web portals for international banking and insurance clients. Write clean, modular, and unit-tested React components adhering to enterprise coding standards and security guidelines.',
    '3-5 years experience developing web applications using React, JavaScript (ES6+), HTML5, and CSS3. Familiarity with RESTful APIs, Git version control, and unit testing frameworks like Jest.',
    'Infosys is seeking a Senior Systems Engineer - Frontend for its development center in Mysuru. Join our digital practice to deliver mission-critical web applications for leading global enterprises.',
    'World-class campus facilities, comprehensive medical insurance, Provident Fund, higher education programs, annual performance appraisal.',
    '2026-03-06T10:00:00Z'::timestamptz,
    'https://careers.infosys.com/job/systems-engineer-frontend-mysuru',
    'published',
    false,
    'https://upload.wikimedia.org/wikipedia/commons/9/95/Infosys_logo.svg'
  ),
  -- 46. [HR Recruiter] Wipro - Senior Technical Recruiter - Cloud & Engineering (Bengaluru)
  (
    '32a33ef9-eac4-404e-b4b3-83817f71081f'::uuid,
    'Wipro',
    'Senior Technical Recruiter - Cloud & Engineering',
    'HR Recruiter',
    'Bengaluru, Karnataka',
    'Hybrid',
    'Full time',
    '4-7 years',
    900000,
    1500000,
    '₹9,00,000 - ₹15,00,000 / yr',
    'INR',
    ARRAY['Tech Recruitment', 'Talent Sourcing', 'LinkedIn Recruiter', 'Interview Coordination', 'ATS Management']::text[],
    'Manage end-to-end technical hiring for Wipro FullStride Cloud Services and digital engineering units in Bengaluru. Source niche talent across AWS, Azure, GCP, and full-stack engineering, conduct screening rounds, and negotiate offers.',
    '4-7 years of technical recruiting experience in IT services or tech product firms. Expert in sourcing via LinkedIn Recruiter, GitHub, and tech communities. Strong communication and candidate closure abilities.',
    'Wipro is expanding its engineering recruiting team in Sarjapur, Bengaluru. As Senior Technical Recruiter, you will spearhead strategic talent acquisition for high-demand cloud and AI delivery teams.',
    'Group medical insurance, annual performance incentives, hybrid working options, transport support, employee wellness programs.',
    '2026-03-12T14:00:00Z'::timestamptz,
    'https://careers.wipro.com/job/senior-tech-recruiter-blr',
    'published',
    false,
    'https://upload.wikimedia.org/wikipedia/commons/a/a0/Wipro_Primary_Logo_Color_RGB.svg'
  ),
  -- 47. [HR Recruiter] Swiggy - Lead HR Recruiter - Business Hiring (Bengaluru)
  (
    'b57f1a24-89d5-4099-81c0-9dc0b66ef459'::uuid,
    'Swiggy',
    'Lead HR Recruiter - Business Hiring',
    'HR Recruiter',
    'Bengaluru, Karnataka',
    'Hybrid',
    'Full time',
    '5-8 years',
    1400000,
    2200000,
    '₹14,00,000 - ₹22,00,000 / yr',
    'INR',
    ARRAY['Full Lifecycle Recruitment', 'Stakeholder Management', 'Salary Negotiation', 'Talent Pipeline', 'Greenhouse']::text[],
    'Lead recruitment for Swiggy central business, finance, and operations leadership roles. Partner with department heads to formulate hiring strategies, define role competencies, and ensure a memorable, transparent candidate experience.',
    '5-8 years in corporate recruiting or high-growth tech recruiting. Proven ability to close mid-to-senior level talent in fast-paced environments. Experience with modern ATS platforms like Greenhouse or Lever.',
    'Swiggy is seeking an experienced Lead HR Recruiter in Bengaluru to drive strategic hiring across our business units. Shape the leadership teams that build India largest on-demand convenience platform.',
    'Comprehensive medical insurance, performance-linked bonuses, flexible hybrid work model, food perks, wellness programs.',
    '2026-03-14T11:30:00Z'::timestamptz,
    'https://swiggy.freshteam.com/jobs/lead-hr-recruiter',
    'published',
    true,
    'https://upload.wikimedia.org/wikipedia/en/thumb/1/12/Swiggy_logo.svg/320px-Swiggy_logo.svg.png'
  ),
  -- 48. [HR Recruiter] Razorpay - Talent Acquisition Specialist - Product & Design (Bengaluru)
  (
    '7ad5299e-facc-4337-b106-461f2750161c'::uuid,
    'Razorpay',
    'Talent Acquisition Specialist - Product & Design',
    'HR Recruiter',
    'Bengaluru, Karnataka',
    'Hybrid',
    'Full time',
    '3-6 years',
    1100000,
    1800000,
    '₹11,00,000 - ₹18,00,000 / yr',
    'INR',
    ARRAY['Design Recruitment', 'Product Hiring', 'Candidate Experience', 'Sourcing', 'Lever']::text[],
    'Drive end-to-end recruitment for Razorpay Design and Product Management teams. Build relationships with top design and product talent, organize design hiring hackathons, and ensure rapid, empathetic candidate feedback loops.',
    '3-6 years experience recruiting Product Managers and Product/UX/UI Designers in tech companies. Strong knack for evaluating design portfolios and understanding product leadership qualities.',
    'Join the Razorpay People team in Bengaluru as a Talent Acquisition Specialist. Partner closely with our Head of Design and VP of Product to scout, engage, and hire India premier creative and product minds.',
    'Medical insurance with dependent coverage, stock option incentives, continuous learning stipend, wellness leave, hybrid hours.',
    '2026-03-13T14:30:00Z'::timestamptz,
    'https://razorpay.com/jobs/talent-acquisition-specialist',
    'published',
    false,
    'https://upload.wikimedia.org/wikipedia/commons/8/89/Razorpay_logo.svg'
  ),
  -- 49. [HR Recruiter] BigBasket - HR Recruiter - Supply Chain & Operations (Bengaluru)
  (
    '40393f4e-a82d-4606-8e07-b5ea63fd592d'::uuid,
    'BigBasket',
    'HR Recruiter - Supply Chain & Operations',
    'HR Recruiter',
    'Bengaluru, Karnataka',
    'Onsite',
    'Full time',
    '2-5 years',
    650000,
    1050000,
    '₹6,50,000 - ₹10,50,000 / yr',
    'INR',
    ARRAY['High-volume Hiring', 'Onboarding', 'Campus Recruitment', 'HR Operations', 'Screening']::text[],
    'Manage talent sourcing and hiring for supply chain hubs, distribution centers, and regional operations teams in Karnataka. Coordinate campus drives, interview panels, background verification, and seamless Day-1 onboarding.',
    '2-5 years in high-volume operations, supply chain, or retail HR recruitment. Excellent interpersonal skills and operational efficiency in handling bulk interview schedules and documentation.',
    'BigBasket is hiring an HR Recruiter in Bengaluru to fuel the expansion of our dark stores and automated fulfillment centers. Bring in energetic operational talent that keeps grocery deliveries running on time.',
    'Health insurance, annual appraisal, grocery discount vouchers, provident fund, gratuity.',
    '2026-03-10T09:00:00Z'::timestamptz,
    'https://careers.bigbasket.com/job/hr-recruiter-operations',
    'published',
    false,
    'https://upload.wikimedia.org/wikipedia/en/thumb/0/07/Bigbasket_Logo.svg/320px-Bigbasket_Logo.svg.png'
  ),
  -- 50. [HR Recruiter] Infosys - Talent Acquisition Executive (Mysuru)
  (
    '87b0b818-7c37-41c7-9536-f5fb99805d80'::uuid,
    'Infosys',
    'Talent Acquisition Executive',
    'HR Recruiter',
    'Mysuru, Karnataka',
    'Hybrid',
    'Full time',
    '2-5 years',
    600000,
    1000000,
    '₹6,00,000 - ₹10,00,000 / yr',
    'INR',
    ARRAY['Campus Hiring', 'Talent Sourcing', 'Offer Management', 'HR Analytics', 'Workday']::text[],
    'Coordinate engineering campus recruitment drives, trainee onboarding, and lateral recruitment operations at the Infosys Mysuru campus. Track candidate pipelines in Workday, schedule technical panels, and prepare offer rollouts.',
    '2-5 years of talent acquisition experience, ideally in large IT organizations or university recruiting programs. Strong organizational, scheduling, and stakeholder communication skills.',
    'Infosys Mysuru campus—the world largest corporate training academy—is looking for an energetic Talent Acquisition Executive to manage campus hiring and entry-level talent onboarding operations.',
    'Comprehensive health benefits, access to campus sports and cultural facilities, PF & gratuity, performance incentives.',
    '2026-03-05T12:00:00Z'::timestamptz,
    'https://careers.infosys.com/job/talent-acquisition-executive-mysuru',
    'published',
    false,
    'https://upload.wikimedia.org/wikipedia/commons/9/95/Infosys_logo.svg'
  );
